import type { LabContent } from '../../app/src/lib/schema-lab';

// Auto-generated by scripts/fixtures-to-ts.mjs — DO NOT EDIT MANUALLY
// Source: fixtures/labs/arp.json

const lab: LabContent = {
  "id": 5,
  "slug": "arp",
  "module": "01-networking",
  "title": "Giao thức ARP",
  "file_path": "labs/01-networking/05-arp.html",
  "estimated_minutes": 30,
  "content_hash": "2fa08fadeab9ba991b40b4ba124f059b383c11f5",
  "updated_at": 1776596733,
  "tldr": [
    {
      "why": "IP là địa chỉ logic (L3), MAC là địa chỉ vật lý (L2). Frame Ethernet yêu cầu MAC đích — app chỉ biết IP — ARP lấp khoảng trống đó. Thiếu ARP thì biết IP cũng không gửi được frame.",
      "whyBreaks": "ARP cache corruption hoặc sai entry → host unreachable dù ping có thể pass (ICMP đi khác). Thường xảy ra sau khi thay NIC (MAC mới), VM migration, hoặc bị ARP spoof. Triệu chứng: kết nối đột ngột drop giữa chừng.",
      "deploymentUse": "Khi deploy VM mới trong cùng subnet: đảm bảo ARP entry cũ (nếu có từ VM trước dùng IP đó) đã expire hoặc flush. Trong Kubernetes: khi pod restart và lấy IP mới, CNI plugin tự gửi Gratuitous ARP để update cache cả cluster.",
      "what": "Tại sao cần ARP"
    },
    {
      "why": "Khi chưa biết MAC của IP đích, không thể unicast. Broadcast FF:FF:FF:FF:FF:FF đến mọi máy trong LAN để tìm đúng chủ. Chi phí: mọi máy phải ngắt CPU để đọc frame — đó là lý do ARP cache quan trọng để tránh broadcast liên tục.",
      "whyBreaks": "LAN quá lớn (/16 = 65534 host) với nhiều máy ARP đồng thời → broadcast storm. Mọi máy liên tục bị ngắt CPU xử lý ARP → CPU spike, throughput giảm. Giải pháp: chia VLAN nhỏ hơn (/24 = 254 host per segment).",
      "deploymentUse": "Khi thiết kế datacenter: giới hạn broadcast domain /24 mỗi VLAN. Hơn 500 host trong 1 subnet = nguy cơ ARP broadcast overhead đáng kể. Kubernetes node trong cùng /24 để ARP hoạt động, L3 routing giữa các /24.",
      "what": "ARP Request = broadcast"
    },
    {
      "why": "Request chứa MAC của người hỏi → máy đích biết reply thẳng về không cần broadcast lại. Tiết kiệm bandwidth và CPU của cả LAN.",
      "whyBreaks": "Không trực tiếp gây lỗi. Nhưng nếu ARP Reply bị block (một số strict firewall policy) → sender không nhận được MAC → gửi ARP Request liên tục (ARP retry) → tăng broadcast overhead.",
      "deploymentUse": "Thường không cần cấu hình gì. Nhưng trong môi trường cloud với virtual switch (OVS, Hyper-V vSwitch): đôi khi cần enable ARP proxy hoặc ARP reflection để các VM giao tiếp được.",
      "what": "ARP Reply = unicast"
    },
    {
      "why": "Sau ARP thành công, MAC được lưu cache 1–5 phút. Tránh broadcast mỗi frame. Nếu cache hết hạn hoặc bị xóa → ARP lại từ đầu. Thấy 'STALE' trong ip neigh = cache sắp hết hạn.",
      "whyBreaks": "ARP cache overflow ('neighbor table overflow' trong dmesg): kernel không lưu được entry mới → ARP fail → host unreachable. Xảy ra khi route nhiều /24 khác nhau qua cùng interface hoặc bị scan ARP từ attacker.",
      "deploymentUse": "Tuning: net.ipv4.neigh.default.gc_thresh1/2/3 để tăng kích thước ARP cache nếu cần route nhiều subnet. Monitoring: watch -n5 'ip neigh show | wc -l' để phát hiện cache overflow sớm.",
      "what": "ARP Cache (ip neigh)"
    },
    {
      "why": "192.168.1.10 cùng subnet → ARP trực tiếp IP đó để lấy MAC. Frame gửi thẳng MAC của đích. Không qua gateway.",
      "whyBreaks": "Host cùng subnet nhưng không trả ARP → STALE → FAILED → ping fail với 'Destination Host Unreachable'. Nguyên nhân: host tắt, VLAN sai, hoặc host disable ARP. Kiểm tra: arping -I eth0 192.168.1.10 để debug.",
      "deploymentUse": "Trong Kubernetes pod network: pod A và pod B cùng node → giao tiếp qua local ARP (veth pair). Pod A và C khác node → qua overlay network (VXLAN/Geneve), không phải ARP trực tiếp. Biết điều này giúp debug pod-to-pod latency.",
      "what": "Ping cùng LAN → ARP IP đích trực tiếp"
    },
    {
      "why": "8.8.8.8 khác subnet → kernel biết phải qua gateway (default route). ARP cho IP gateway (192.168.1.1), lấy MAC gateway. Frame gửi MAC gateway — KHÔNG phải MAC của 8.8.8.8. Gateway bóc IP gốc, đóng frame mới, tiếp tục định tuyến.",
      "whyBreaks": "Gateway đổi MAC (thay thiết bị, failover) → ARP cache cũ → tất cả outbound traffic đi vào hư không → internet fail mặc dù IP gateway vẫn đúng. Fix: ip neigh flush dev eth0 để force ARP lại. Keepalived dùng Gratuitous ARP để tránh vấn đề này.",
      "deploymentUse": "Khi VPS report 'no internet' đột ngột: check ip neigh show | grep gateway-IP. Nếu FAILED hoặc STALE lâu → flush và ARP lại. Trong cloud provider thay đổi underlying hardware → MAC gateway thay đổi → cần flush ARP cache.",
      "what": "Ping ngoài LAN → ARP IP của gateway"
    },
    {
      "why": "Attacker gửi ARP Reply giả nhanh hơn, khai báo MAC của attacker ứng với IP gateway/victim → cả 2 máy lưu MAC sai vào cache → mọi traffic đi qua attacker (MITM). Không cần crack mật khẩu — chỉ cần ở cùng LAN.",
      "whyBreaks": "Victim không detect được: mọi traffic vẫn đi được (attacker forward tiếp), latency tăng nhẹ. Dấu hiệu: 2 IP có cùng MAC trong ip neigh, hoặc latency đột biến trong LAN. Sau khi MITM: attacker đọc/sửa traffic không encrypt.",
      "deploymentUse": "Phòng ngừa: Dynamic ARP Inspection (DAI) trên managed switch, dùng HTTPS/TLS cho mọi service (MITM không đọc được), VPN trong LAN không tin cậy (khách sạn, cafe). Trên cloud: security group ngăn VM khác spoof ARP nhờ hypervisor enforcement.",
      "what": "ARP Spoofing"
    }
  ],
  "walkthrough": [
    {
      "step": 1,
      "what": "Bước 1 — Kiểm tra ARP cache trước khi gửi frame",
      "why": "Kernel Linux kiểm tra bảng ARP (ip neigh) trước khi phát broadcast. Nếu cache còn hiệu lực → dùng ngay, không broadcast. Cache hit = tiết kiệm ~1ms và tránh làm phiền cả LAN.",
      "whyBreaks": "ARP cache FAILED sau flush → ping fail với 'Destination Host Unreachable' dù host vẫn alive. Kernel sẽ thử ARP lại tự động nhưng có latency. Khi debug 'intermittent connection loss': check ip neigh state trước.",
      "observeWith": "ip neigh show  # Xem toàn bộ cache với state\nip neigh show nud reachable  # Chỉ entries đang reliable\nwatch -n2 'ip neigh show'  # Real-time theo dõi thay đổi cache",
      "code": "# Xem bảng ARP cache hiện tại\nip neigh show\n\n# Output mẫu:\n# 192.168.1.1 dev eth0 lladdr aa:bb:cc:dd:ee:01 REACHABLE\n# 192.168.1.10 dev eth0 lladdr aa:bb:cc:dd:ee:10 STALE"
    },
    {
      "step": 2,
      "what": "Bước 2 — Gửi ARP Request broadcast",
      "why": "Cache miss → kernel phát frame broadcast (Eth dst=FF:FF:FF:FF:FF:FF) hỏi 'Ai có IP 192.168.1.10?'. Mọi máy trong LAN nhận nhưng chỉ máy có IP đó reply. Capture được bằng tcpdump để xem thực tế.",
      "whyBreaks": "Không thấy ARP Reply sau Request → host không tồn tại, host tắt, hoặc host disable ARP (một số firewall config). Phân biệt: nếu thấy Request broadcast nhưng không có Reply → vấn đề ở phía đích, không phải sender.",
      "observeWith": "sudo tcpdump -i eth0 -n arp  # Xem 'arp who-has' (request) và 'arp reply' (reply)\n# Request: Ethernet dst=ff:ff:ff:ff:ff:ff (broadcast)\n# Reply: Ethernet dst=<MAC của người hỏi> (unicast)\nsudo arping -I eth0 -c 1 192.168.1.10  # Test ARP thủ công, xem có reply không",
      "code": "# Xem ARP broadcast trên dây bằng tcpdump\nsudo tcpdump -i eth0 -n arp\n\n# Hoặc dùng arping để thủ công gửi ARP request\nsudo arping -I eth0 -c 1 192.168.1.10",
      "failModes": [
        {
          "symptom": "Mạng chậm đột ngột, mọi máy trong LAN bị ảnh hưởng dù không có traffic lớn",
          "evidence": "dmesg hoặc /var/log/kern.log: 'net_ratelimit: X callbacks suppressed' kèm tcpdump thấy hàng trăm ARP Request/giây từ nhiều src MAC khác nhau — dấu hiệu ARP storm do loop hoặc misconfigured NIC bonding"
        }
      ],
      "fixSteps": [
        {
          "step": "Xác định nguồn storm: đếm ARP rate trên switch port hoặc tcpdump",
          "command": "sudo tcpdump -i eth0 -n arp | awk '{print $NF}' | sort | uniq -c | sort -rn | head -20"
        },
        {
          "step": "Cô lập port nghi ngờ trên managed switch để dừng storm",
          "command": "sudo ip link set eth0 down  # tạm thời isolate interface đang bị flood"
        }
      ]
    },
    {
      "step": 3,
      "what": "Bước 3 — Nhận ARP Reply unicast",
      "why": "Máy đích gửi Reply unicast về: 'IP 192.168.1.10 có MAC aa:bb:cc:dd:ee:10'. Unicast vì Request đã cung cấp MAC người hỏi — không cần broadcast. Kernel lưu vào cache ngay.",
      "whyBreaks": "Sau khi flush cache và ping thành công: ip neigh show phải hiện entry mới với state REACHABLE. Nếu vẫn FAILED sau ping thành công → ARP hoạt động nhưng có gì đó sai với neighbor subsystem (hiếm, thường do kernel bug hoặc container network misconfiguration).",
      "observeWith": "ip neigh flush all && ping -c 1 192.168.1.10 && ip neigh show\n# Sau lệnh này: thấy entry 192.168.1.10 REACHABLE với MAC đúng\n# Timing: ARP resolve xảy ra trong <1ms khi host alive",
      "code": "# Quan sát cache được cập nhật sau khi ping\nip neigh flush all           # Xóa cache\nping -c 1 192.168.1.10       # Trigger ARP\nip neigh show                # Xem entry mới thêm vào"
    },
    {
      "step": 4,
      "what": "Bước 4 — Ping ra Internet: ARP for gateway",
      "why": "Khi ping 8.8.8.8, kernel so sánh với routing table — 8.8.8.8 không cùng subnet → next hop là default gateway (192.168.1.1). ARP cho 192.168.1.1, không phải 8.8.8.8. Frame gửi với MAC gateway. Dev hay nhầm điểm này khi debug MITM.",
      "whyBreaks": "ip neigh flush + ping 8.8.8.8: tcpdump phải thấy ARP request cho 192.168.1.1, không phải 8.8.8.8. Nếu không thấy ARP cho gateway → routing table sai (không có default route) → 'Network unreachable' thay vì ARP timeout.",
      "observeWith": "ip route  # Xem 'default via X.X.X.X' — đây là IP sẽ bị ARP\nsudo tcpdump -i eth0 arp -n  # Capture song song khi ping 8.8.8.8\n# Confirm: ARP request hỏi gateway IP, không phải 8.8.8.8",
      "code": "# Xem routing table để hiểu kernel quyết định next hop thế nào\nip route\n# Output: default via 192.168.1.1 dev eth0\n\n# Khi ping 8.8.8.8 → ARP xảy ra cho 192.168.1.1\nsudo tcpdump -i eth0 arp &\nping -c 1 8.8.8.8\nkill %1"
    },
    {
      "step": 5,
      "what": "Bước 5 — ARP Spoofing: đầu độc cache",
      "why": "Attacker gửi gratuitous ARP Reply (không được yêu cầu): '192.168.1.1 có MAC là attacker_mac'. Nạn nhân cập nhật cache với MAC sai → gửi traffic tới attacker thay vì gateway. Dùng arpspoof (dsniff) hoặc Scapy. Phòng: DAI trên managed switch.",
      "whyBreaks": "ARP không authenticate sender — bất kỳ máy nào cũng có thể claim bất kỳ IP nào. Đây là lỗ hổng by design của <a href=\"https://datatracker.ietf.org/doc/html/rfc826\" target=\"_blank\">RFC 826</a>. Không thể 'patch' ARP — phải phòng ở tầng khác (DAI switch, VPN, TLS).",
      "observeWith": "ip neigh show | awk '{print $5}' | sort | uniq -d  # Tìm MAC trùng lặp\n# Nếu có output → 2 IP chia sẻ 1 MAC → dấu hiệu spoofing hoặc NIC bonding\narp-scan --localnet  # Scan ARP toàn LAN, so sánh MAC với expected",
      "code": "# Phát hiện ARP spoofing bằng arp-scan hoặc xem bất thường\n# (trên Linux - chỉ để học, KHÔNG dùng tấn công thật)\narp -a | sort -t'.' -k4 -n  # Xem toàn bộ cache, tìm MAC trùng lặp\n\n# Phát hiện: 2 IP có cùng MAC = dấu hiệu spoofing\n# ip neigh | awk '{print $5}' | sort | uniq -d",
      "failModes": [
        {
          "symptom": "Traffic đến gateway bị mất hoặc đi sai hướng, latency LAN tăng đột biến ~2-5ms",
          "evidence": "ip neigh show | awk '/192.168.1.1/{print}' trả ra MAC không khớp với MAC thật của gateway — ví dụ: '192.168.1.1 dev eth0 lladdr de:ad:be:ef:00:01 REACHABLE' trong khi MAC thật gateway là aa:bb:cc:dd:ee:01"
        }
      ],
      "fixSteps": [
        {
          "step": "Xác nhận MAC gateway thật bằng cách hỏi trực tiếp switch hoặc so sánh với baseline",
          "command": "sudo arping -I eth0 -c 2 192.168.1.1 | grep 'reply from'"
        },
        {
          "step": "Xóa ARP cache entry bị nhiễm, buộc re-resolve",
          "command": "sudo ip neigh del 192.168.1.1 dev eth0 && ping -c 1 192.168.1.1"
        },
        {
          "step": "Thêm static ARP entry cho gateway để chặn spoof tiếp theo (tạm thời)",
          "command": "sudo ip neigh add 192.168.1.1 lladdr aa:bb:cc:dd:ee:01 dev eth0 nud permanent"
        }
      ],
      "automateScript": {
        "lang": "bash",
        "code": "#!/bin/bash\n# Phát hiện duplicate MAC (ARP spoofing indicator) trên LAN\n# Dùng arp-scan, chạy cron mỗi 5 phút\nINTERFACE=${1:-eth0}\nDUPS=$(sudo arp-scan --interface=\"$INTERFACE\" --localnet 2>/dev/null \\\n  | awk '/DUP/{print $1, $2}' | sort -u)\nif [ -n \"$DUPS\" ]; then\n  echo \"[ALERT $(date '+%Y-%m-%d %H:%M:%S')] Duplicate MAC detected on $INTERFACE:\"\n  echo \"$DUPS\"\n  logger -t arp-monitor \"ALERT: duplicate MAC — $DUPS\"\nfi",
        "note": "Cron: */5 * * * * /usr/local/bin/arp-monitor.sh eth0. Cần gói arp-scan. Log vào syslog để alert tập trung."
      }
    },
    {
      "step": 6,
      "what": "Bước 6 — Xem ARP trực tiếp bằng Wireshark/tcpdump",
      "why": "Thực hành capture là cách duy nhất để thực sự thấy ARP hoạt động. Wireshark filter 'arp' sẽ tách biệt hoàn toàn. Quan sát: Dst broadcast → Request; Dst unicast → Reply. Đây là kiến thức cốt lõi khi debug 'host unreachable'.",
      "whyBreaks": "Chạy tcpdump trên interface sai (vlan vs physical, docker0 vs eth0) → không thấy ARP dù nó đang xảy ra. Trong Docker/Kubernetes: ARP xảy ra trên virtual interface (veth, docker0, cni0) không phải eth0.",
      "observeWith": "sudo tcpdump -i eth0 -n -vvv arp  # -vvv để thấy full ARP fields\n# Đọc: 'arp who-has TARGET tell SENDER' = Request\n# Đọc: 'arp reply TARGET is-at MAC' = Reply\nip link show  # List all interfaces — chọn đúng interface",
      "code": "# Terminal 1: Capture ARP\nsudo tcpdump -i eth0 -n -vvv arp\n\n# Terminal 2: Flush cache rồi ping để trigger ARP\nip neigh flush all\nping -c 1 192.168.1.10\n\n# Wireshark filter: arp\n# Xem: Who has 192.168.1.10? Tell 192.168.1.5"
    },
    {
      "step": 7,
      "what": "Bước 7 — Gratuitous ARP và IP conflict detection",
      "why": "Khi interface up, Linux tự gửi Gratuitous ARP: broadcast '192.168.1.5 có MAC là ...'. Mục đích: (1) cập nhật cache mọi máy với MAC mới, (2) phát hiện IP conflict — nếu có ai reply thì có 2 máy cùng IP. Đây cũng là cơ chế failover VIP (VRRP/keepalived) dùng.",
      "whyBreaks": "Sau keepalived failover mà không gửi Gratuitous ARP → các host trong LAN giữ cache cũ (MAC node primary) → traffic đến VIP vẫn đi tới node đã down → downtime kéo dài đến khi cache expire (~5 phút). Gratuitous ARP là bước bắt buộc trong failover.",
      "observeWith": "sudo tcpdump -i eth0 arp  # Xem Gratuitous ARP khi arping -A\n# Gratuitous: sender IP = target IP (host tự hỏi chính địa chỉ của nó)\narping -D -I eth0 192.168.1.5  # Duplicate Address Detection: exit 1 = conflict",
      "code": "# Gửi Gratuitous ARP thủ công (ví dụ sau failover)\narping -A -I eth0 -c 3 192.168.1.5\n\n# Hoặc dùng arping để kiểm tra IP conflict:\narping -D -I eth0 192.168.1.5\n# Exit code 1 = có conflict"
    }
  ],
  "quiz": [
    {
      "q": "Máy tính biết IP đích 192.168.1.10. Tại sao vẫn cần ARP trước khi gửi frame?",
      "options": [
        "Để kiểm tra xem host còn sống không",
        "Frame Ethernet cần MAC đích, không thể điền IP vào ô MAC",
        "ARP giúp tìm đường định tuyến (routing)",
        "Để mã hóa dữ liệu trước khi gửi"
      ],
      "correct": 1,
      "whyCorrect": "Ethernet frame header có trường <strong>Destination MAC</strong> — bắt buộc phải là MAC 6 byte. Không có cú pháp nào để điền IP vào đó. ARP là bước bắt buộc để lấy MAC từ IP trước khi đóng gói frame.",
      "whyOthersWrong": {
        "0": "Kiểm tra host còn sống là nhiệm vụ của ICMP ping (L3), không phải ARP (L2).",
        "2": "Routing là việc của IP (L3) và routing table. ARP chỉ hoạt động trong 1 LAN, không định tuyến.",
        "3": "Mã hóa thuộc TLS/L4-L6, hoàn toàn không liên quan ARP."
      }
    },
    {
      "q": "Ping 8.8.8.8 từ host 192.168.1.5. ARP request sẽ hỏi MAC của IP nào?",
      "options": [
        "8.8.8.8 — IP đích cần ping",
        "192.168.1.5 — IP của host gửi",
        "192.168.1.1 — IP của default gateway",
        "Không có ARP vì 8.8.8.8 là Internet"
      ],
      "correct": 2,
      "whyCorrect": "8.8.8.8 không cùng subnet → kernel tra routing table → next hop là default gateway 192.168.1.1. Frame phải tới gateway trước → ARP hỏi MAC của 192.168.1.1, không phải 8.8.8.8. MAC của 8.8.8.8 không tồn tại trong LAN này.",
      "whyOthersWrong": {
        "0": "8.8.8.8 ở mạng khác — ARP chỉ hoạt động trong cùng 1 broadcast domain (LAN). Không thể ARP qua router.",
        "1": "ARP chính host gửi là vô nghĩa. Gratuitous ARP khác — gửi để thông báo, không phải hỏi.",
        "3": "Sai — ARP vẫn xảy ra, nhưng cho IP gateway. Nếu không có ARP thì không có frame nào đi được."
      }
    },
    {
      "q": "ARP Request gửi tới Ethernet address nào?",
      "options": [
        "MAC của gateway",
        "MAC của IP đích (dùng bảng cũ)",
        "FF:FF:FF:FF:FF:FF (broadcast)",
        "Địa chỉ multicast 01:00:5E:..."
      ],
      "correct": 2,
      "whyCorrect": "ARP Request là broadcast vì chưa biết MAC đích — đó chính là lý do phải hỏi. FF:FF:FF:FF:FF:FF là broadcast address của Ethernet, mọi máy trong LAN sẽ nhận và đọc.",
      "whyOthersWrong": {
        "0": "Nếu đã biết MAC gateway thì không cần ARP nữa — đây là circular reasoning.",
        "1": "Nếu đã có bảng MAC cũ thì không cần ARP request — dùng cache luôn.",
        "3": "Multicast 01:00:5E dùng cho IGMP/mDNS, không phải ARP."
      }
    },
    {
      "q": "ARP Reply được gửi bằng cách nào?",
      "options": [
        "Broadcast — để mọi máy cập nhật cache",
        "Unicast — về thẳng máy đã gửi Request",
        "Multicast — tiết kiệm bandwidth",
        "Gửi qua router tới người hỏi"
      ],
      "correct": 1,
      "whyCorrect": "ARP Request chứa MAC của người hỏi trong trường Sender MAC. Máy đích đọc được → gửi Reply unicast về MAC đó. Không cần broadcast lại — tiết kiệm CPU mọi máy trong LAN.",
      "whyOthersWrong": {
        "0": "Broadcast Reply gây tốn kém — mọi máy phải xử lý. Thiết kế ARP dùng unicast vì đã biết địa chỉ người hỏi.",
        "2": "ARP không dùng multicast. Multicast yêu cầu nhóm đăng ký trước.",
        "3": "ARP là giao thức L2, không đi qua router. Router là thiết bị L3, ARP chỉ trong 1 LAN."
      }
    },
    {
      "q": "Attacker trong cùng LAN gửi ARP Reply giả: 'IP 192.168.1.1 có MAC=attacker_mac'. Hậu quả?",
      "options": [
        "Không có hậu quả — victim sẽ verify bằng cách hỏi lại",
        "Victim lưu MAC sai vào cache → traffic tới gateway đi qua attacker (MITM)",
        "Switch phát hiện và block frame giả",
        "Router từ chối frame có MAC sai"
      ],
      "correct": 1,
      "whyCorrect": "ARP không có cơ chế xác thực — máy nhận Reply sẽ tin tưởng và cập nhật cache ngay lập tức, kể cả khi không gửi Request trước (gratuitous ARP). Victim gửi traffic tới attacker_mac thay vì gateway → attacker forward tiếp để tránh lộ, đọc/sửa nội dung.",
      "whyOthersWrong": {
        "0": "ARP không có cơ chế verify — đây là weakness by design. <a href=\"https://datatracker.ietf.org/doc/html/rfc826\" target=\"_blank\">RFC 826</a> không có authentication.",
        "2": "Switch thông thường (unmanaged) không inspect ARP. Chỉ managed switch với Dynamic ARP Inspection (DAI) mới block.",
        "3": "Router chỉ xử lý L3 (IP). Frame vào router dựa trên MAC — nếu MAC đúng là router thì router nhận bình thường."
      }
    },
    {
      "q": "Lệnh nào hiển thị ARP cache trên Linux hiện đại?",
      "options": [
        "arp -a",
        "ip neigh show",
        "netstat -r",
        "route -n"
      ],
      "correct": 1,
      "whyCorrect": "<code>ip neigh show</code> là lệnh hiện đại (iproute2), hiển thị neighbor table (ARP cache) kèm state (REACHABLE/STALE/FAILED). <code>arp -a</code> cũng hoạt động nhưng là legacy (net-tools), ít thông tin hơn.",
      "whyOthersWrong": {
        "0": "<code>arp -a</code> hoạt động nhưng là lệnh cũ (deprecated). Trên nhiều distro mới không cài net-tools mặc định.",
        "2": "<code>netstat -r</code> hiển thị routing table (L3), không phải ARP cache (L2).",
        "3": "<code>route -n</code> cũng là routing table, không liên quan ARP."
      }
    },
    {
      "q": "Sau khi ip neigh flush all, ping 192.168.1.10 thành công. Điều gì xảy ra với ARP?",
      "options": [
        "Ping dùng IP trực tiếp, không cần ARP",
        "ARP Request broadcast → Reply từ 192.168.1.10 → cache được populate → ICMP gửi được",
        "Ping fail vì cache trống",
        "Kernel tự điền MAC từ routing table"
      ],
      "correct": 1,
      "whyCorrect": "Cache trống → kernel phát ARP Request broadcast. 192.168.1.10 reply với MAC của nó. Kernel lưu vào cache. Lúc này mới gửi được ICMP Echo Request trong frame Ethernet với MAC đúng. Toàn bộ xảy ra trong vài ms.",
      "whyOthersWrong": {
        "0": "ICMP (ping) chạy trên IP (L3), nhưng để xuống dây phải đóng gói trong frame L2 — frame cần MAC đích. Không thể bỏ qua ARP.",
        "2": "Ping sẽ thành công sau khi ARP hoàn thành — không fail.",
        "3": "Routing table chứa IP next-hop, không chứa MAC. MAC phải lấy qua ARP."
      }
    }
  ],
  "flashcards": [
    {
      "front": "ARP là gì và giải quyết vấn đề gì?",
      "back": "Address Resolution Protocol — ánh xạ IP (L3) sang MAC (L2). Giải quyết vấn đề: frame Ethernet cần MAC đích nhưng app chỉ biết IP.",
      "why": "Đây là bridge bắt buộc giữa L2 và L3. Thiếu ARP thì không gửi được frame dù biết IP — hiểu điều này giúp debug 'host unreachable' nhanh hơn."
    },
    {
      "front": "ARP Request gửi tới địa chỉ gì? Tại sao?",
      "back": "Ethernet broadcast FF:FF:FF:FF:FF:FF. Vì chưa biết MAC đích — phải hỏi hết mọi máy trong LAN.",
      "why": "Broadcast tốn CPU của mọi máy trong LAN → đó là lý do ARP cache quan trọng. Hiểu điều này giúp explain tại sao LAN lớn (nhiều máy) dễ bị storm broadcast."
    },
    {
      "front": "ARP Reply gửi unicast hay broadcast?",
      "back": "Unicast — về thẳng MAC của máy đã gửi Request (lấy từ trường Sender MAC trong Request).",
      "why": "Thiết kế tối ưu: đã có đủ thông tin để unicast, không làm phiền cả LAN. Hiểu điểm này để không nhầm 'ARP luôn broadcast'."
    },
    {
      "front": "Ping 8.8.8.8 từ 192.168.1.5: ARP hỏi MAC của IP nào?",
      "back": "MAC của 192.168.1.1 (default gateway) — không phải 8.8.8.8. 8.8.8.8 khác subnet → phải qua gateway.",
      "why": "Điểm dev hay nhầm nhất. Frame chỉ đi được trong 1 LAN — MAC đích luôn là next hop (gateway), không phải IP đích cuối cùng. Quan trọng khi debug MITM và routing."
    },
    {
      "front": "ARP cache lifetime trên Linux? State là gì?",
      "back": "Thường 60s (REACHABLE) → 1 phút thêm (STALE) → FAILED. Xem bằng ip neigh show. Flush bằng ip neigh flush all.",
      "why": "Cache hết hạn → ARP lại → tốn thời gian. Trong môi trường production, cache flap (thay MAC liên tục) thường báo hiệu ARP spoofing hoặc failover."
    },
    {
      "front": "ARP Spoofing hoạt động thế nào?",
      "back": "Attacker gửi ARP Reply giả (không cần được hỏi trước): 'IP_victim/gateway có MAC=attacker_mac'. Nạn nhân tin → cache nhiễm → MITM.",
      "why": "ARP không có authentication — đây là điểm yếu by design của <a href=\"https://datatracker.ietf.org/doc/html/rfc826\" target=\"_blank\">RFC 826</a>. Biết điều này để hiểu tại sao cần DAI trên switch và tại sao không tin mạng LAN lạ (khách sạn, cafe)."
    },
    {
      "front": "Gratuitous ARP là gì? Dùng khi nào?",
      "back": "ARP Request/Reply mà sender IP = target IP (host tự khai IP của chính nó). Dùng: (1) thông báo MAC mới sau failover, (2) phát hiện IP conflict, (3) VRRP/keepalived.",
      "why": "Keepalived/VRRP gửi Gratuitous ARP khi VIP chuyển sang node backup — mọi máy cập nhật cache với MAC mới. Không có Gratuitous ARP thì traffic bị blackhole trong ~5 phút đến khi cache cũ expire."
    },
    {
      "front": "Dynamic ARP Inspection (DAI) là gì?",
      "back": "Tính năng trên managed switch: kiểm tra ARP packet có hợp lệ không (đối chiếu với DHCP snooping table). Port không tin cậy mà gửi ARP Reply giả → switch block.",
      "why": "DAI là biện pháp phòng ARP spoofing ở L2 — không cần sửa host. Quan trọng trong môi trường datacenter và enterprise. Nếu chỉ có unmanaged switch → dùng VPN."
    },
    {
      "front": "Tại sao LAN với 1000 máy dễ bị ARP broadcast storm?",
      "back": "Mỗi ARP Request = broadcast đến 999 máy khác. Nếu nhiều máy đồng thời ARP → CPU của mọi host phải xử lý hàng nghìn broadcast/giây.",
      "why": "Đây là lý do VLAN ra đời: chia LAN lớn thành nhiều broadcast domain nhỏ. /24 = 254 host; /22 = 1022 host — scaling linear theo số host."
    },
    {
      "front": "ip neigh show — các state là gì?",
      "back": "REACHABLE: mới dùng, tin được. STALE: chưa dùng lâu, có thể cũ. FAILED: ARP thất bại. PERMANENT: config cứng, không expire.",
      "why": "STALE không có nghĩa sai — khi cần gửi frame, kernel probe lại. FAILED = host unreachable. Debug 'neighbor table overflow' xảy ra khi có quá nhiều IP /24 lạ."
    },
    {
      "front": "Proxy ARP là gì?",
      "back": "Router trả lời ARP thay cho host ở mạng khác, cung cấp MAC của chính router. Host nghĩ đích ở cùng LAN nhưng thực ra qua router.",
      "why": "Dùng trong một số VPN và legacy network. Nhược: che giấu network boundary, khó debug. Trên Linux: net.ipv4.conf.eth0.proxy_arp=1."
    }
  ],
  "try_at_home": [
    {
      "cmd": "# Flush cache trước để đảm bảo có ARP mới\nsudo ip neigh flush all\n\n# Capture ARP trên terminal 1\nsudo tcpdump -i eth0 -n -vvv arp\n\n# Trên terminal 2: ping để trigger\nping -c 1 192.168.1.1",
      "why": "Quan sát ARP Request/Reply trực tiếp trên dây — thấy broadcast và unicast bằng mắt thường",
      "observeWith": "# Request: Ethernet dst=ff:ff:ff:ff:ff:ff (broadcast)\n# 'arp who-has 192.168.1.1 tell 192.168.1.5'\n# Reply: Ethernet dst=<MAC requester> (unicast)\n# 'arp reply 192.168.1.1 is-at aa:bb:cc:dd:ee:01'"
    },
    {
      "cmd": "# Xem cache đầy đủ với state\nip neigh show\n\n# Xem chỉ entries đang REACHABLE\nip neigh show nud reachable\n\n# Xóa 1 entry cụ thể\nsudo ip neigh del 192.168.1.10 dev eth0",
      "why": "Xem ARP cache và hiểu trạng thái REACHABLE/STALE — cơ sở để debug 'host unreachable'",
      "observeWith": "# State lifecycle: REACHABLE → STALE (idle) → FAILED (ARP không trả lời)\n# STALE không có nghĩa lỗi — kernel probe lại khi cần gửi frame\n# FAILED = host unreachable thật sự"
    },
    {
      "cmd": "# -D = Duplicate Address Detection mode\n# Exit code 1 = có conflict\narping -D -I eth0 -c 2 192.168.1.5\necho \"Exit: $?\"  # 0=OK, 1=conflict",
      "why": "Kiểm tra IP conflict bằng Gratuitous ARP — quan trọng khi thêm IP mới hoặc sau failover",
      "observeWith": "# Nếu exit 1: có máy khác reply Gratuitous ARP → IP đang được dùng\n# sudo tcpdump -i eth0 arp  # Song song để thấy ai reply\n# Trong prod: chạy trước khi assign IP mới cho VM/container"
    },
    {
      "cmd": "# Xem routing table — đọc default via để biết gateway\nip route\n\n# Flush cache, ping 8.8.8.8, xem ARP xảy ra cho IP nào\nsudo ip neigh flush all\nsudo tcpdump -i eth0 arp -n &\nping -c 1 8.8.8.8\nsleep 1 && kill %1\nip neigh show  # Chỉ thấy gateway IP, không thấy 8.8.8.8",
      "why": "Thấy đường đi ARP khi ping Internet — xác nhận 'frame dùng MAC gateway chứ không phải MAC đích'",
      "observeWith": "# ip neigh show sau ping 8.8.8.8: chỉ có entry cho 192.168.1.1 (gateway)\n# Không có entry cho 8.8.8.8 — đây là bằng chứng ARP chỉ xảy ra trong LAN\n# Wireshark filter: arp.tpa == 8.8.8.8 → không có packet nào"
    },
    {
      "cmd": "# Tìm 2 IP có cùng MAC address (dấu hiệu spoofing)\nip neigh show | awk '{print $5}' | sort | uniq -d\n\n# Quét ARP toàn bộ LAN và so sánh\nsudo arp-scan --localnet 2>/dev/null | awk '/([0-9a-f]{2}:){5}/' | sort -t$'\\t' -k2\n\n# Nếu thấy MAC trùng với 2+ IP → điều tra ngay",
      "why": "Phát hiện dấu hiệu ARP spoofing trong mạng — kỹ năng cần thiết cho bảo mật và audit",
      "observeWith": "# Output của ip neigh: cột 5 là MAC address\n# uniq -d chỉ in ra các MAC xuất hiện 2+ lần\n# arp-scan --localnet: mỗi dòng là 'IP\\tMAC\\tVendor' — sort -k2 để group theo MAC\n# Legitimate: bonding/teaming có thể share MAC → verify với hardware team"
    }
  ],
  "diagram": {
    "type": "custom",
    "component": "ArpPlayground"
  }
};

export default lab;
