import type { LabContent } from '../../app/src/lib/schema-lab';

// Auto-generated by scripts/fixtures-to-ts.mjs — DO NOT EDIT MANUALLY
// Source: fixtures/labs/dhcp.json

const lab: LabContent = {
  "id": 6,
  "slug": "dhcp",
  "module": "01-networking",
  "title": "Giao thức DHCP",
  "file_path": "labs/01-networking/06-dhcp.html",
  "estimated_minutes": 35,
  "content_hash": "45cde8530bd7c0c6f12f1fc9c9e1116d1a09b57c",
  "updated_at": 1776596764,
  "tldr": [
    {
      "why": "Client chưa có IP → chỉ có cách broadcast. src=0.0.0.0 vì chưa có địa chỉ, dst=255.255.255.255 để đến tất cả host trong LAN.",
      "whyBreaks": "Nếu không có DHCP server nào trả lời Discover (timeout), client sẽ gán IP tự động 169.254.x.x (APIPA) — dấu hiệu nhận biết DHCP fail hoàn toàn. Kiểm tra: tcpdump port 67 xem Discover có đi ra không.",
      "deploymentUse": "Trên VPS cloud mới tạo, DHCP Discover là bước đầu tiên khi boot. AWS/GCP dùng DHCP server tại 169.254.169.254 (link-local). Nếu security group block UDP 67/68 → VM không lấy được IP → SSH không vào được.",
      "name": "Discover",
      "step": "D",
      "src_dst": "0.0.0.0 → 255.255.255.255",
      "port": "68 → 67",
      "payload": "xid, MAC client"
    },
    {
      "why": "Server vẫn broadcast vì client chưa có IP để unicast tới. Server đề xuất IP từ pool, cùng các tham số mạng.",
      "whyBreaks": "Có Discover nhưng không có Offer → DHCP server chưa chạy, pool cạn, hoặc relay agent không config đúng. Kiểm tra: systemctl status isc-dhcp-server và cat /var/lib/dhcp/dhcpd.leases xem pool còn không.",
      "deploymentUse": "Khi Terraform tạo VPC subnet, cần chỉ định enable_dhcp=true (AWS) hoặc đặt DHCP options set đúng — không thì VM boot lên không có IP, health check fail, auto-scaling group bị stuck.",
      "name": "Offer",
      "step": "O",
      "src_dst": "192.168.1.1 → 255.255.255.255",
      "port": "67 → 68",
      "payload": "IP đề xuất, lease time, gateway, DNS"
    },
    {
      "why": "Client broadcast để các DHCP server khác biết nó chọn server nào. Tại thời điểm này IP vẫn chưa chính thức được gán.",
      "whyBreaks": "Nếu Wireshark thấy Discover → Offer → Request nhưng không có Ack → IP client muốn đã bị conflict hoặc hết lease validity. Server sẽ gửi DHCPNAK. Client phải restart DORA từ đầu.",
      "deploymentUse": "Trong Kubernetes, kubelet dùng DHCP Request để lấy IP cho node. Nếu DHCP server trả NACK (pool hết hoặc conflict) → node không join cluster, pod scheduling fail.",
      "name": "Request",
      "step": "R",
      "src_dst": "0.0.0.0 → 255.255.255.255",
      "port": "68 → 67",
      "payload": "IP được chọn, server identifier"
    },
    {
      "why": "Server xác nhận chính thức. Client nhận ACK mới bắt đầu dùng IP. Nếu Ack mang NACK → client phải Discover lại.",
      "whyBreaks": "Có ACK nhưng client vẫn không lên mạng: (1) gateway option sai → no routing, (2) DNS option sai → domain không resolve, (3) DHCP client service crash sau khi nhận ACK. Verify: ip addr, ip route, cat /etc/resolv.conf sau khi DORA xong.",
      "deploymentUse": "Cloud init script chạy sau DHCP ACK. Nếu ACK cung cấp DNS server sai → cloud-init không download package → provisioning fail. AWS metadata server (169.254.169.254) cũng cần DHCP cấp đúng route.",
      "name": "Ack",
      "step": "A",
      "src_dst": "192.168.1.1 → 255.255.255.255",
      "port": "67 → 68",
      "payload": "IP xác nhận, lease time, options đầy đủ"
    },
    {
      "why": "Tại T1=50% lease, client unicast tới server gốc để gia hạn. Nếu thành công, lease được reset về đầu.",
      "whyBreaks": "DHCP server bị thay thế hoặc di chuyển IP trong khi lease đang active → client unicast T1 đến IP cũ không còn tồn tại → fail silent đến T2 rồi broadcast rebind. Trong thời gian này service vẫn chạy nhưng IP sắp hết hạn.",
      "deploymentUse": "Staging environment thường restart DHCP server khi deploy. Nếu VM có lease 24h và T1 fail do DHCP server restart, client sẽ tự phục hồi ở T2 — biết điều này tránh panic khi thấy log 'T1 renewal failed'.",
      "name": "Renew (50%)",
      "step": "T1",
      "src_dst": "client → server (unicast)",
      "port": "68 → 67",
      "payload": "Request gia hạn"
    },
    {
      "why": "Server gốc không phản hồi T1 → client broadcast rebind. Bất kỳ DHCP server nào cũng có thể xác nhận.",
      "whyBreaks": "Nếu T2 rebind cũng fail (không DHCP server nào phản hồi) → đến 100% lease, client mất IP → network down đột ngột. Triệu chứng: 'mạng tự mất sau vài giờ'. Debug: check DHCP server uptime vs lease expiry time.",
      "deploymentUse": "Monitoring DHCP trên production: alert khi thấy nhiều T2 rebind request — đây là early warning DHCP infrastructure có vấn đề trước khi client thực sự mất IP và service down.",
      "name": "Rebind (87.5%)",
      "step": "T2",
      "src_dst": "client → 255.255.255.255",
      "port": "68 → 67",
      "payload": "Request rebind"
    },
    {
      "why": "Broadcast không vượt được router. Relay agent (router) nhận broadcast, đổi thành unicast gửi tới DHCP server ở subnet khác.",
      "whyBreaks": "Quên config relay agent (ip helper-address) khi thêm subnet mới → toàn bộ VM trong subnet đó không lấy được IP. Lỗi im lặng: client loop Discover vô hạn, không có error message rõ ràng.",
      "deploymentUse": "Khi mở rộng VPC thêm subnet mới (Terraform aws_subnet), phải đảm bảo route table và DHCP relay config đúng. AWS tự xử lý relay nội bộ, nhưng on-prem/hybrid cloud cần config tay trên router.",
      "name": "Relay Agent",
      "step": "Relay",
      "src_dst": "client → server (qua router)",
      "port": "67 → 67",
      "payload": "Forward broadcast thành unicast"
    }
  ],
  "walkthrough": [
    {
      "step": 1,
      "what": "DHCPDISCOVER — Client kêu cứu trong LAN",
      "why": "Client vừa boot, chỉ có MAC address. Nó phải broadcast vì chưa có IP — đây là điểm khởi đầu bắt buộc. Không có Discover thì không có gì xảy ra tiếp theo.",
      "whyBreaks": "Nếu không thấy Discover trên tcpdump → interface chưa UP hoặc dhclient chưa chạy. Nếu thấy Discover nhưng không có Offer → DHCP server không nghe trên interface đó hoặc firewall block UDP 67. Đây là 2 failure mode hoàn toàn khác nhau cần debug khác nhau.",
      "observeWith": "sudo tcpdump -i any port 67 or port 68 -n — xem src=0.0.0.0 dst=255.255.255.255 cho Discover. Chạy song song sudo dhclient -v eth0 ở terminal khác để trigger DORA. journalctl -u dhclient -f xem log real-time.",
      "code": "# Capture DHCP traffic trên VM Linux\nsudo tcpdump -i eth0 -n 'udp port 67 or udp port 68'\n\n# Hoặc bằng Wireshark filter:\n# udp.port == 67 || udp.port == 68\n\n# Force client gửi Discover ngay (Debian/Ubuntu):\nsudo dhclient -v eth0"
    },
    {
      "step": 2,
      "what": "DHCPOFFER — Server đề xuất IP",
      "why": "Server nhận Discover, chọn IP trống từ pool, rồi broadcast Offer. Tại sao vẫn broadcast? Vì client chưa có IP để unicast tới. Server có thể nhớ IP đề xuất trong thời gian ngắn chờ Request từ client.",
      "whyBreaks": "Pool cạn là lý do thường gặp nhất khi server không gửi Offer. Mỗi VM dev clone không release lease → sau vài tháng pool .50-.200 đầy hết. Dấu hiệu: dhcpd.leases có hàng trăm entry, nhiều đã expired nhưng server chưa reap.",
      "observeWith": "cat /var/lib/dhcp/dhcpd.leases | grep -c 'lease' — đếm số lease. grep 'binding state active' /var/lib/dhcp/dhcpd.leases | wc -l — đếm lease đang active. So sánh với kích thước pool để biết còn bao nhiêu IP trống.",
      "code": "# Xem DHCP pool configuration (isc-dhcp-server)\ncat /etc/dhcp/dhcpd.conf\n\n# Xem lease hiện tại của server\ncat /var/lib/dhcp/dhcpd.leases\n\n# Ví dụ cấu hình pool:\n# subnet 192.168.1.0 netmask 255.255.255.0 {\n#   range 192.168.1.50 192.168.1.200;\n#   option routers 192.168.1.1;\n#   option domain-name-servers 8.8.8.8;\n#   default-lease-time 86400;\n# }",
      "failModes": [
        {
          "symptom": "Client không lấy được IP — máy mới boot hiển thị 169.254.x.x (APIPA), mọi DHCPDISCOVER không nhận Offer",
          "evidence": "grep 'no free leases' /var/log/syslog cho thấy: 'dhcpd: no free leases on subnet 192.168.1.0' — pool .50-.200 (151 địa chỉ) đã hết sạch"
        }
      ],
      "fixSteps": [
        {
          "step": "Đếm số lease active và so sánh với pool size để xác nhận pool hết",
          "command": "grep -c 'binding state active' /var/lib/dhcp/dhcpd.leases"
        },
        {
          "step": "Tìm lease đã expired nhưng chưa được reap (thường từ VM clone không release)",
          "command": "awk '/lease/{ip=$2} /binding state active/{print ip}' /var/lib/dhcp/dhcpd.leases | sort -u | wc -l"
        },
        {
          "step": "Restart dhcpd để force reap expired lease (ngắn hạn) hoặc mở rộng pool range trong dhcpd.conf",
          "command": "sudo systemctl restart isc-dhcp-server && sudo journalctl -u isc-dhcp-server -n 20"
        }
      ],
      "automateScript": {
        "lang": "bash",
        "code": "#!/bin/bash\n# Monitor DHCP pool usage, alert khi > 80% đầy\n# Chạy cron mỗi 15 phút\nLEASE_FILE=\"/var/lib/dhcp/dhcpd.leases\"\nPOOL_SIZE=${1:-151}  # range .50-.200\nACTIVE=$(grep -c 'binding state active' \"$LEASE_FILE\" 2>/dev/null || echo 0)\nPCT=$(( ACTIVE * 100 / POOL_SIZE ))\necho \"[$(date '+%Y-%m-%d %H:%M')] DHCP pool: $ACTIVE/$POOL_SIZE leases active ($PCT%)\"\nif [ \"$PCT\" -gt 80 ]; then\n  logger -t dhcp-monitor \"WARN: DHCP pool ${PCT}% full ($ACTIVE/$POOL_SIZE)\"\n  echo \"WARN: Pool ${PCT}% full — consider expanding range in dhcpd.conf\"\nfi",
        "note": "Cron: */15 * * * * /usr/local/bin/dhcp-pool-monitor.sh 151. Điều chỉnh POOL_SIZE khớp với range trong dhcpd.conf."
      }
    },
    {
      "step": 3,
      "what": "DHCPREQUEST — Client xác nhận chọn IP",
      "why": "Client broadcast Request để tất cả DHCP server trong LAN biết nó đã chọn server nào. Các server không được chọn sẽ giải phóng IP đã dự trữ. Đây là bước 'thông báo công khai' để tránh IP conflict.",
      "whyBreaks": "Nếu Wireshark thấy Discover → Offer → Request nhưng không có Ack: IP client chọn có thể đã bị conflict (máy khác đang dùng) hoặc server state không nhất quán sau restart. Server sẽ gửi DHCPNAK — tìm packet type DHCPNAK trong capture.",
      "observeWith": "sudo tcpdump -i any port 67 or port 68 -n -vv | grep -E 'DHCP|Discover|Offer|Request|ACK|NAK' — lọc ra các bước DORA. Xem field 'DHCP-Message Option 53' trong output verbose để phân biệt từng loại message.",
      "code": "# Xem IP hiện tại của interface (sau khi hoàn thành DORA)\nip addr show eth0\n\n# Xem DHCP lease client đang giữ (NetworkManager)\nnmcli device show eth0 | grep -E 'IP4|DHCP'\n\n# Xem lease file của client\ncat /var/lib/dhcp/dhclient.leases"
    },
    {
      "step": 4,
      "what": "DHCPACK — Server xác nhận chính thức",
      "why": "Server ghi lease vào database rồi gửi Ack. Chỉ khi nhận được Ack, client mới thực sự cấu hình IP, gateway, DNS vào interface. Trước Ack, IP vẫn chỉ là 'đang đàm phán'.",
      "whyBreaks": "Nhận ACK nhưng ip addr không thấy IP: dhclient crash sau khi nhận ACK (check journalctl -u dhclient). Hoặc gateway trong ACK là sai subnet → ip route không tạo được default route → có IP nhưng không reach internet.",
      "observeWith": "ip addr show eth0 | grep 'inet ' — phải thấy IP với flag 'dynamic'. ip route show default — phải có default route qua gateway. cat /etc/resolv.conf — phải có nameserver. Ping cả 3 cấp: gateway, 8.8.8.8, google.com.",
      "code": "# Verify IP được gán sau DORA\nip addr show eth0\nip route  # Gateway đã có chưa?\ncat /etc/resolv.conf  # DNS đã config chưa?\n\n# Ping gateway để verify kết nối\nping -c 1 $(ip route | awk '/default/ {print $3}')"
    },
    {
      "step": 5,
      "what": "Lease renewal — Gia hạn trước khi hết hạn",
      "why": "Không gia hạn = IP bị thu hồi = mất kết nối mạng đột ngột. T1 và T2 là buffer tránh gián đoạn dịch vụ. Hiểu cơ chế này giúp debug 'mạng tự mất sau vài giờ/ngày'.",
      "whyBreaks": "VM để ngủ (suspend) qua đêm rồi wake up: lease đã expired trong khi ngủ. Khi wake, client cố gắng rebind bằng IP cũ nhưng server đã thu hồi và cấp cho máy khác → DHCPNAK → DORA lại. Dấu hiệu: mạng mất 2-5 giây khi wake from sleep.",
      "observeWith": "journalctl -u dhclient --since '1 hour ago' | grep -E 'DHCP|bound|renew|expire' — xem lịch sử renewal. cat /var/lib/dhcp/dhclient.leases | grep -A5 'expire' — xem thời điểm expire của lease hiện tại.",
      "code": "# Xem lease time còn lại (dhclient)\nsudo dhclient -v -r eth0  # Release\nsudo dhclient -v eth0     # Renew (DORA lại)\n\n# Xem lease details\ncat /var/lib/dhcp/dhclient.leases | grep -A10 'lease'\n\n# Kiểm tra thời điểm expire\nip -details addr show eth0"
    },
    {
      "step": 6,
      "what": "DHCP Relay — khi server ở subnet khác",
      "why": "Enterprise network thường có 1 DHCP server trung tâm phục vụ nhiều subnet. Relay agent (interface ip helper) trên router đóng vai trò 'phiên dịch viên' giữa broadcast và unicast. Không có relay → DHCP chỉ hoạt động trong 1 subnet.",
      "whyBreaks": "Thêm VLAN mới mà quên config ip helper-address trên router → toàn bộ VM trong VLAN mới không lấy được IP. Debug: ping từ router đến DHCP server trước, rồi check relay config. Lỗi hay gặp: SERVERS trong relay config trỏ sai IP server.",
      "observeWith": "sudo tcpdump -i eth0 port 67 -n trên relay agent — xem DHCP packet đến interface và relay forward đi. Trên DHCP server: sudo tcpdump -i any port 67 -n xem có nhận packet từ relay agent IP không (src sẽ là IP relay, không phải IP client).",
      "code": "# Cấu hình relay agent (isc-dhcp-relay)\nsudo apt install isc-dhcp-relay\n\n# /etc/default/isc-dhcp-relay\n# SERVERS=\"10.0.0.1\"  # DHCP server IP\n# INTERFACES=\"eth0 eth1\"  # Interfaces cần relay\n\n# Verify relay đang chạy\nsudo systemctl status isc-dhcp-relay\n\n# Cisco router (ip helper-address)\n# interface GigabitEthernet0/1\n#   ip helper-address 10.0.0.1",
      "failModes": [
        {
          "symptom": "VM trong VLAN mới không lấy được IP, tcpdump trên relay agent không thấy DHCP packet đến từ VLAN đó",
          "evidence": "sudo tcpdump -i eth0.20 port 67 -n không có output dù client gửi Discover — interface VLAN trunk chưa được thêm vào INTERFACES trong /etc/default/isc-dhcp-relay"
        }
      ],
      "fixSteps": [
        {
          "step": "Kiểm tra INTERFACES trong relay config có bao gồm VLAN interface mới không",
          "command": "cat /etc/default/isc-dhcp-relay | grep INTERFACES"
        },
        {
          "step": "Thêm VLAN interface vào relay và restart",
          "command": "sed -i 's/INTERFACES=\"/INTERFACES=\"eth0.20 /' /etc/default/isc-dhcp-relay && sudo systemctl restart isc-dhcp-relay"
        }
      ]
    },
    {
      "step": 7,
      "what": "Debug DHCP fail — không lấy được IP",
      "why": "Mục tiêu thực tế của lab DHCP: debug được khi có sự cố. Biết DORA flow → biết lỗi ở bước nào. Không có Offer → server chết hoặc pool hết. Có Offer nhưng không có Ack → conflict hoặc server config sai.",
      "whyBreaks": "Debug checklist theo thứ tự: (1) Interface UP? → ip link. (2) Discover đi ra? → tcpdump. (3) Offer về? → nếu không, server/pool problem. (4) Ack về? → nếu không, NACK/conflict. (5) IP được apply? → ip addr. Bỏ qua bước nào là debug mù.",
      "observeWith": "journalctl -u dhclient -f — log real-time của DHCP client, thấy từng bước DORA và error message rõ ràng. Kết hợp sudo tcpdump -i any port 67 or port 68 -n ở terminal khác để thấy packet level đồng thời.",
      "code": "# 1. Check interface có UP không (L1/L2)\nip link show eth0\n\n# 2. Force DORA, xem verbose output\nsudo dhclient -v eth0 2>&1\n\n# 3. Capture để thấy bước nào fail\nsudo tcpdump -i eth0 -n -vv 'udp port 67 or udp port 68'\n\n# 4. Nếu không có Offer: check DHCP server running\n# sudo systemctl status isc-dhcp-server\n\n# 5. Fallback: set static IP tạm\nsudo ip addr add 192.168.1.99/24 dev eth0\nsudo ip route add default via 192.168.1.1"
    }
  ],
  "quiz": [
    {
      "q": "Tại sao DHCPDISCOVER dùng src=0.0.0.0 thay vì IP thực?",
      "options": [
        "Để ẩn danh, bảo mật",
        "Client chưa có IP, 0.0.0.0 là địa chỉ đặc biệt nghĩa là 'chưa có IP'",
        "0.0.0.0 là địa chỉ broadcast tiêu chuẩn",
        "Để DHCP server dễ nhận ra packet Discover"
      ],
      "correct": 1,
      "whyCorrect": "Client vừa boot chưa được gán IP nào. TCP/IP yêu cầu source IP để gửi packet. <a href=\"https://datatracker.ietf.org/doc/html/rfc2131\" target=\"_blank\">RFC 2131</a> quy định 0.0.0.0 dùng khi client chưa có địa chỉ — đây là cách hợp lệ duy nhất để gửi UDP khi không có IP.",
      "whyOthersWrong": {
        "0": "0.0.0.0 không liên quan bảo mật — packet vẫn broadcast toàn LAN, mọi người đều thấy. MAC address còn cố định hơn.",
        "2": "Địa chỉ broadcast là 255.255.255.255. 0.0.0.0 là 'unspecified address' khác hoàn toàn.",
        "3": "Phân biệt Discover không phải do src IP — server nhìn vào DHCP message type trong option 53 của payload."
      }
    },
    {
      "q": "Client nhận được DHCPOFFER rồi — tại sao bước tiếp theo (Request) vẫn phải broadcast thay vì unicast thẳng tới server?",
      "options": [
        "Vì client chưa biết IP của server",
        "Để thông báo cho các DHCP server khác trong LAN biết server nào được chọn",
        "Unicast tốn bandwidth hơn broadcast",
        "Đây là lỗi thiết kế của giao thức DHCP"
      ],
      "correct": 1,
      "whyCorrect": "Trong LAN có thể có nhiều DHCP server, tất cả đều gửi Offer. Khi client broadcast Request (kèm server identifier), các server không được chọn biết để giải phóng IP đã dự trữ. Đây là cơ chế chống lãng phí tài nguyên.",
      "whyOthersWrong": {
        "0": "Client biết IP server từ DHCPOFFER — field 'server identifier'. Lý do broadcast không phải vì không biết IP.",
        "2": "Ngược lại — broadcast tốn tài nguyên hơn unicast vì tất cả host đều phải xử lý. Broadcast ở đây là có mục đích cụ thể.",
        "3": "Đây là thiết kế có chủ đích, không phải lỗi. <a href=\"https://datatracker.ietf.org/doc/html/rfc2131\" target=\"_blank\">RFC 2131</a> giải thích rõ lý do."
      }
    },
    {
      "q": "Lease time 24 giờ. Client sẽ bắt đầu renew lần đầu vào thời điểm nào?",
      "options": [
        "Sau 24 giờ (khi hết hạn)",
        "Sau 21 giờ (T2 = 87.5%)",
        "Sau 12 giờ (T1 = 50%)",
        "Sau 1 giờ (T1 = 1/24)"
      ],
      "correct": 2,
      "whyCorrect": "T1 = 50% lease time = 12 giờ. Đây là lần renew đầu tiên — client unicast tới DHCP server gốc. Mục đích là gia hạn sớm để còn nhiều thời gian xử lý nếu server không phản hồi.",
      "whyOthersWrong": {
        "0": "Khi hết hạn (100%) là quá muộn — client đã mất IP. T1 và T2 là để đảm bảo không bao giờ rơi vào trường hợp này.",
        "1": "T2 = 87.5% = 21 giờ là mốc rebind — chỉ xảy ra nếu T1 thất bại. Đây là bước cuối trước khi mất IP.",
        "3": "Không có mốc T=1/24 trong DHCP. Công thức là T1=50%, T2=87.5% của total lease time."
      }
    },
    {
      "q": "VM ở subnet 10.0.1.0/24. DHCP server ở subnet 10.0.0.0/24. DHCPDISCOVER của VM không tới được server. Giải pháp đúng là?",
      "options": [
        "Đặt DHCP server ở cùng subnet 10.0.1.0/24",
        "Cấu hình DHCP relay agent trên router giữa 2 subnet",
        "Dùng static IP thay DHCP",
        "Tăng TTL của DHCPDISCOVER lên 255"
      ],
      "correct": 1,
      "whyCorrect": "Đây chính xác là use case của DHCP relay. Relay agent trên router nhận broadcast từ 10.0.1.x, convert thành unicast packet gửi tới 10.0.0.x (DHCP server). Server trả lời unicast về relay, relay forward lại client.",
      "whyOthersWrong": {
        "0": "Về kỹ thuật cũng được, nhưng không scale — enterprise có hàng chục subnet, không thể đặt DHCP server ở mọi subnet. Relay sinh ra để giải quyết vấn đề này.",
        "2": "Static IP giải quyết được nhưng mất hoàn toàn lợi ích tự động hoá của DHCP, không scale.",
        "3": "TTL không liên quan — vấn đề là broadcast bị router chặn theo thiết kế, không phải TTL hết."
      }
    },
    {
      "q": "Wireshark capture cho thấy DHCPDISCOVER → DHCPOFFER → DHCPREQUEST nhưng KHÔNG có DHCPACK. Nguyên nhân có thể là?",
      "options": [
        "Client từ chối IP server đề xuất",
        "DHCP server bận xử lý request khác",
        "IP client muốn Request bị conflict (đã có máy khác dùng), server gửi NACK",
        "Network bị mất gói ở L1"
      ],
      "correct": 2,
      "whyCorrect": "Khi server nhận Request nhưng IP đó đã bị conflict hoặc không còn hợp lệ, server gửi DHCPNAK (negative acknowledgment) thay vì ACK. Client nhận NACK phải bắt đầu DORA lại. Wireshark capture sẽ thấy NACK packet.",
      "whyOthersWrong": {
        "0": "DHCP không có cơ chế client từ chối offer — client chỉ chọn server bằng Request. Nếu muốn IP khác, client có thể không respond Offer rồi chờ timeout.",
        "1": "DHCP server xử lý sequential và rất nhanh — không có khái niệm 'bận'. Nếu bận thật thì delay, không phải mất Ack.",
        "3": "L1 mất gói thì ngay cả DISCOVER cũng không đi được, không thể capture đến bước Request."
      }
    },
    {
      "q": "Lệnh nào đúng để xem DHCP lease client đang giữ trên Linux?",
      "options": [
        "cat /etc/resolv.conf",
        "ip route show",
        "cat /var/lib/dhcp/dhclient.leases",
        "sudo netstat -an | grep 67"
      ],
      "correct": 2,
      "whyCorrect": "<code>dhclient</code> lưu lease info (IP, gateway, DNS, expire time, server ID) vào <code>/var/lib/dhcp/dhclient.leases</code>. File này cho biết IP từ đâu, khi nào hết hạn, server nào cấp.",
      "whyOthersWrong": {
        "0": "<code>/etc/resolv.conf</code> chỉ chứa DNS nameserver. Đúng là DHCP có thể set DNS vào file này, nhưng không phải lease info.",
        "1": "<code>ip route</code> cho thấy gateway đang dùng, không cho biết IP từ DHCP hay static, hay khi nào hết hạn.",
        "3": "<code>netstat -an | grep 67</code> cho thấy socket đang open trên port 67, không phải lease info."
      }
    },
    {
      "q": "Server production dùng DHCP hay Static IP? Tại sao?",
      "options": [
        "DHCP — tự động, không cần config tay",
        "Static IP — IP cố định để DNS, firewall rule, monitoring không bị lỗi",
        "Tùy loại server, không có quy tắc chung",
        "DHCP nhưng với lease time rất dài (năm)"
      ],
      "correct": 1,
      "whyCorrect": "Server production cần static IP vì: DNS A record trỏ vào IP đó, firewall/security group rule dựa trên IP, monitoring alert, SSH known_hosts — tất cả sẽ fail nếu IP thay đổi. DHCP mạnh cho workstation/container, không phải server dài hạn.",
      "whyOthersWrong": {
        "0": "DHCP tiện nhưng IP có thể thay đổi. Khi đó DNS sẽ sai, firewall sẽ block, monitoring mất tín hiệu — downtime ngay lập tức.",
        "2": "Thực tế có quy tắc rõ ràng: infrastructure (server, router, switch, printer) → static; user device, VM dev → DHCP.",
        "3": "Lease time dài không giải quyết được vấn đề — IP vẫn có thể đổi khi renew. DHCP reservation (bind MAC↔IP) là lựa chọn tốt hơn, nhưng phức tạp hơn static."
      }
    }
  ],
  "flashcards": [
    {
      "front": "DORA là gì? 4 bước?",
      "back": "Discover → Offer → Request → Ack. Quy trình client tự động lấy IP từ DHCP server.",
      "why": "DORA là từ khoá debug quan trọng nhất khi máy không lấy được IP. Biết 4 bước = biết kiểm tra Wireshark xem bị kẹt ở đâu."
    },
    {
      "front": "Tại sao DHCPDISCOVER dùng src=0.0.0.0?",
      "back": "Client chưa có IP nào. 0.0.0.0 là 'unspecified address' theo <a href=\"https://datatracker.ietf.org/doc/html/rfc2131\" target=\"_blank\">RFC 2131</a> — cách hợp lệ để gửi UDP khi chưa có địa chỉ.",
      "why": "Hiểu điều này giải thích toàn bộ lý do DHCP phải dùng broadcast — không thể unicast khi không có source IP."
    },
    {
      "front": "DHCP dùng port nào? Client và Server khác nhau thế nào?",
      "back": "Port 67: DHCP Server lắng nghe (nhận Discover + Request). Port 68: DHCP Client lắng nghe (nhận Offer + Ack).",
      "why": "Cần biết khi debug bằng tcpdump/Wireshark. Filter 'udp port 67 or 68' để bắt toàn bộ DORA."
    },
    {
      "front": "Tại sao DHCPREQUEST vẫn broadcast dù client đã biết IP server?",
      "back": "Để thông báo cho các DHCP server khác trong LAN biết server nào được chọn, các server còn lại giải phóng IP đã dự trữ.",
      "why": "Môi trường có nhiều DHCP server → Request broadcast là cơ chế phối hợp tránh lãng phí pool. Bỏ bước này = các server khác giữ IP dự trữ mãi."
    },
    {
      "front": "T1 và T2 trong lease renewal là bao nhiêu? Ý nghĩa?",
      "back": "T1=50% lease time: unicast renew tới server gốc. T2=87.5% lease time: broadcast rebind tới bất kỳ server nào.",
      "why": "Hiểu T1/T2 = debug được 'mạng tự mất sau vài giờ'. Thường là DHCP server chết, client không renew được ở T1, đến T2 rebind cũng fail, đến 100% mất IP."
    },
    {
      "front": "DHCP Relay Agent là gì? Tại sao cần?",
      "back": "Relay agent (thường là router) chuyển DHCP broadcast thành unicast để vượt qua router tới DHCP server ở subnet khác.",
      "why": "Enterprise có 1 DHCP server trung tâm cho nhiều subnet. Không có relay, mỗi subnet phải có server riêng — không scale. Cisco: 'ip helper-address', Linux: isc-dhcp-relay."
    },
    {
      "front": "DHCPNAK là gì? Xảy ra khi nào?",
      "back": "Negative Acknowledgment — server từ chối Request. Xảy ra khi IP đã conflict, client ở subnet sai, hoặc lease không còn hợp lệ.",
      "why": "Debug quan trọng: thấy Discover→Offer→Request nhưng không có Ack → tìm NACK packet trong Wireshark. Client phải Discover lại từ đầu."
    },
    {
      "front": "Khi nào dùng Static IP, khi nào dùng DHCP?",
      "back": "Static: server, database, router, gateway, printer — bất cứ thứ gì cần IP cố định lâu dài. DHCP: workstation, VM dev, container, user device.",
      "why": "Sai lựa chọn này gây ra downtime thực sự. Server dùng DHCP: IP đổi → DNS sai → mọi client fail. Workstation dùng static: xung đột IP, admin nightmare."
    },
    {
      "front": "Lệnh nào force renew DHCP trên Linux?",
      "back": "sudo dhclient -v eth0 (renew). Hoặc: sudo dhclient -r eth0 (release) rồi sudo dhclient eth0 (DORA lại).",
      "why": "Cần khi debug DHCP hoặc khi muốn đổi IP mà không reboot. '-v' verbose cho thấy từng bước DORA trong terminal."
    },
    {
      "front": "Wireshark filter để capture DORA?",
      "back": "udp.port == 67 || udp.port == 68",
      "why": "Lệnh này bắt toàn bộ DHCP traffic. Xem được 4 message DORA, check src/dst IP, payload option. Thiếu bước nào = debug tại đó."
    },
    {
      "front": "DHCP lease file lưu ở đâu trên Linux?",
      "back": "Client: /var/lib/dhcp/dhclient.leases. Server: /var/lib/dhcp/dhcpd.leases.",
      "why": "File lease chứa IP, expire time, server ID, DNS, gateway. Đọc file này để biết IP đang dùng từ đâu, khi nào hết hạn."
    },
    {
      "front": "Giải thích 'ip addr show eth0' sau DORA thành công trông thế nào?",
      "back": "inet 192.168.1.50/24 brd 192.168.1.255 scope global dynamic eth0 — từ khoá 'dynamic' nghĩa là từ DHCP.",
      "why": "Từ khoá 'dynamic' phân biệt IP từ DHCP vs static. Đây là cách nhanh nhất verify DORA đã thành công."
    }
  ],
  "try_at_home": [
    {
      "cmd": "# Terminal 1: capture DHCP traffic\nsudo tcpdump -i eth0 -n -vv 'udp port 67 or udp port 68'\n\n# Terminal 2: force client renew\nsudo dhclient -v -r eth0 && sudo dhclient -v eth0",
      "why": "Xem toàn bộ 4 bước DORA trong thực tế — verify từng packet src/dst IP và payload",
      "observeWith": "Trong tcpdump output, xác nhận: (1) Discover src=0.0.0.0 dst=255.255.255.255, (2) Offer src=server-IP dst=255.255.255.255 kèm 'Your IP', (3) Request src=0.0.0.0 broadcast lại, (4) ACK src=server-IP với IP xác nhận. Cả 4 bước phải có trong vòng 1-2 giây."
    },
    {
      "cmd": "cat /var/lib/dhcp/dhclient.leases\n\n# Xem IP và flag dynamic\nip addr show | grep -A2 'dynamic'\n\n# Xem DNS đã được DHCP set\ncat /etc/resolv.conf",
      "why": "Đọc lease file để xem IP từ đâu, khi nào hết hạn, server nào cấp — thông tin quan trọng cho debug",
      "observeWith": "Trong dhclient.leases tìm các trường: fixed-address (IP được cấp), expire (thời điểm hết hạn), option dhcp-server-identifier (server IP), option domain-name-servers (DNS từ DHCP). ip addr phải có từ 'dynamic' — nếu không thấy thì IP đang là static."
    },
    {
      "cmd": "# Trên máy DHCP server\nsudo systemctl stop isc-dhcp-server\n\n# Trên client — xem log verbose, sẽ thấy timeout sau Discover\nsudo dhclient -v eth0\n\n# Bật lại\nsudo systemctl start isc-dhcp-server",
      "why": "Simulate DHCP fail: tắt DHCP server rồi renew — xem Wireshark kẹt ở Discover, không có Offer",
      "observeWith": "Khi server tắt, dhclient -v phải hiển thị nhiều dòng 'DHCPDISCOVER on eth0' lặp lại với delay tăng dần (1s, 2s, 4s — exponential backoff). Không có dòng 'DHCPOFFER' nào. Sau khi bật server lại, chạy lại dhclient -v và verify OFFER → ACK → 'bound to X.X.X.X'."
    },
    {
      "cmd": "# Xem IP hiện tại (dynamic từ DHCP)\nip addr show eth0 | grep inet\n\n# Set static IP thủ công\nsudo ip addr flush eth0\nsudo ip addr add 192.168.1.200/24 dev eth0\nsudo ip route add default via 192.168.1.1\n\n# Xem lại — không có flag 'dynamic' nữa\nip addr show eth0 | grep inet\n\n# Khôi phục DHCP\nsudo ip addr flush eth0\nsudo dhclient eth0",
      "why": "So sánh trực tiếp DHCP vs Static — thấy được sự khác biệt trong ip addr output",
      "observeWith": "So sánh output ip addr trước và sau: IP từ DHCP có suffix 'dynamic' trong output; static IP không có 'dynamic'. Sau khi flush và set static, ip route phải thêm default route tay vì DHCP không còn tự cấp. Sau khi dhclient khôi phục, cả IP lẫn default route đều tự động quay lại."
    },
    {
      "cmd": "# Trên DHCP server\ncat /var/lib/dhcp/dhcpd.leases | grep -A6 'lease'\n\n# Format dễ đọc hơn\ndhcp-lease-list 2>/dev/null || cat /var/lib/dhcp/dhcpd.leases | grep -E 'lease|binding|hardware|client-hostname'",
      "why": "Xem DHCP server đang cấp IP cho những máy nào — thực hành đọc lease database của server",
      "observeWith": "Mỗi lease entry phải có: địa chỉ IP (lease X.X.X.X), MAC (hardware ethernet), binding state (active/free/expired), starts/ends timestamp. Đếm số entry 'binding state active' và so sánh với range pool để biết còn bao nhiêu IP trống."
    }
  ],
  "diagram": {
    "type": "custom",
    "component": "DhcpPlayground"
  }
};

export default lab;
