import type { LabContent } from '../../app/src/lib/schema-lab';

// Auto-generated by scripts/fixtures-to-ts.mjs — DO NOT EDIT MANUALLY
// Source: fixtures/labs/tcp-udp.json

const lab: LabContent = {
  "id": 3,
  "slug": "tcp-udp",
  "module": "01-networking",
  "title": "Tìm hiểu UDP/TCP",
  "file_path": "labs/01-networking/03-tcp-udp.html",
  "estimated_minutes": 40,
  "content_hash": "2436b3e8322334d86ed5f28ebbbb71b23518aa8d",
  "updated_at": 1776596784,
  "tldr": [
    {
      "why": "Dùng khi dữ liệu phải đến đủ và đúng thứ tự (web, SSH, DB). TCP đảm bảo bằng cách retransmit khi mất gói — không cần tự xử lý mất gói trong application code.",
      "whyBreaks": "Dùng TCP cho game multiplayer real-time: retransmit gói cũ block gói mới → Head-of-Line blocking → lag spike không kiểm soát được, đặc biệt khi mạng có >1% packet loss.",
      "deploymentUse": "Mọi service cần data integrity: HTTP/HTTPS (nginx), database (MySQL port 3306, Postgres 5432), SSH (port 22), file transfer. Nếu mất 1 byte là corrupt → dùng TCP.",
      "what": "TCP — Transmission Control Protocol"
    },
    {
      "why": "Dùng khi tốc độ quan trọng hơn độ chính xác (DNS, VoIP, game, streaming). Mỗi ms latency trong game = cảm giác lag rõ ràng — TCP overhead quá đắt.",
      "whyBreaks": "Dùng UDP cho HTTP web thông thường mà không có reliability layer (như QUIC) → trang hiển thị thiếu/lỗi khi mạng kém, không có cơ chế retransmit tự động.",
      "deploymentUse": "DNS (port 53), game server (Unity/Unreal thường UDP), video streaming (WebRTC), VoIP (SIP/RTP), monitoring (syslog UDP 514, SNMP UDP 161). Khi latency quan trọng hơn completeness.",
      "what": "UDP — User Datagram Protocol"
    },
    {
      "why": "TCP cần xác nhận cả 2 chiều đều thông trước khi gửi data. Nếu bỏ qua bước này, 1 bên có thể gửi vào hư không khi mạng bất đối xứng.",
      "whyBreaks": "SYN flood attack: attacker gửi hàng nghìn SYN giả, server tốn memory/CPU cho half-open connections đang chờ ACK → server không nhận được connection hợp lệ (DoS). Phòng: SYN cookies.",
      "deploymentUse": "Khi debug connection slow: đo RTT của handshake bằng tcpdump timestamp. 3 RTT cho handshake + 1-2 RTT cho TLS → baseline latency trước khi data đi = lý do cần CDN/edge gần user.",
      "what": "3-way Handshake: SYN → SYN-ACK → ACK"
    },
    {
      "why": "Port phân biệt nhiều service trên cùng 1 IP. Không có port, server không biết giao packet cho nginx hay ssh. Well-known cần root để bảo vệ khỏi giả mạo.",
      "whyBreaks": "Bind service non-root trên port < 1024: Permission denied. Bind port đang dùng: Address already in use (TIME_WAIT chưa hết hoặc service chưa dừng hẳn). Cả hai là lỗi deploy phổ biến.",
      "deploymentUse": "nginx production: chạy master process root để bind :80/:443, worker process drop xuống www-data. Node.js dev thường dùng :3000/:8080 (không cần root). Container: map host port 80 → container port 3000.",
      "what": "Port 0–65535, well-known < 1024"
    },
    {
      "why": "Overhead lớn = tốn bandwidth hơn. Với DNS (hàng tỷ query/giây), tiết kiệm 12 byte mỗi packet = tiết kiệm hàng GB/giây băng thông mạng toàn cầu.",
      "whyBreaks": "Không liên quan trực tiếp đến lỗi — nhưng với IoT device gửi 100 byte payload, TCP header chiếm 20% overhead. Trên mạng cellular đắt tiền, UDP tiết kiệm chi phí bandwidth đáng kể.",
      "deploymentUse": "Chọn giao thức IoT sensor: MQTT over TCP (reliable, overhead cao hơn) vs UDP custom protocol (minimal overhead). Khi battery và data plan quan trọng → UDP. Khi data phải đến đủ → TCP/MQTT.",
      "what": "TCP header 20–60 byte vs UDP header 8 byte"
    },
    {
      "why": "QUIC xây reliability ở tầng app trên UDP, tránh Head-of-Line blocking của TCP — khi mất 1 stream không chặn stream khác. Đây là lý do HTTP/3 nhanh hơn HTTP/2.",
      "whyBreaks": "Corporate firewall block UDP outbound ngoài port 53/123 → HTTP/3 bị block → browser fallback sang HTTP/2 TCP → không gây lỗi visible nhưng performance tệ hơn kỳ vọng.",
      "deploymentUse": "Cloudflare, nginx 1.25+, Caddy hỗ trợ HTTP/3. Bật bằng thêm Alt-Svc header. Cần mở port UDP 443 trên firewall/security group ngoài TCP 443. Verify bằng: curl --http3 https://yourdomain.com.",
      "what": "HTTP/3 dùng UDP (QUIC)"
    }
  ],
  "walkthrough": [
    {
      "step": 1,
      "what": "Mở TCP listener với nc",
      "why": "Hiểu port binding thực tế — nc tạo 1 process lắng nghe port 9000. Không có process listen thì TCP SYN nhận RST ngay (connection refused). Đây là nền tảng để debug 'connection refused'.",
      "whyBreaks": "Nếu quên mở server trước khi connect → Connection refused ngay lập tức. Nếu port đang dùng bởi process khác → Address already in use. Cả 2 lỗi này chiếm >50% câu hỏi debug của junior dev.",
      "observeWith": "ss -tlnp | grep 9000  # Xem process nào đang listen port 9000\nsudo tcpdump -i lo -n 'port 9000' -v  # Capture gói trên loopback khi connect",
      "code": "# Terminal 1 — khởi động TCP server\nnc -l 9000\n\n# Terminal 2 — kết nối TCP client\nnc 127.0.0.1 9000\n# Gõ text bất kỳ → hiện ở Terminal 1\n# Ctrl+C để đóng"
    },
    {
      "step": 2,
      "what": "Capture 3-way handshake bằng tcpdump",
      "why": "Nhìn tận mắt SYN/SYN-ACK/ACK là cách học nhanh nhất. Flag [S] = SYN, [S.] = SYN-ACK, [.] = ACK. Khi debug 'connection timeout', tcpdump cho biết SYN đi được không.",
      "whyBreaks": "Nếu chỉ thấy SYN mà không thấy SYN-ACK → firewall hoặc server không listen. Nếu thấy SYN + RST → port đóng. Nếu không thấy gì → packet bị drop (firewall DROP). Phân biệt 3 pattern này là core network debug skill.",
      "observeWith": "sudo tcpdump -i lo -n 'port 9000' -v  # Flag: [S]=SYN, [S.]=SYN-ACK, [.]=ACK, [R]=RST\n# Đọc output: client:port > server:port Flags [S], seq N",
      "code": "# Terminal 1 — capture trên loopback\nsudo tcpdump -i lo -n 'port 9000' -v\n\n# Terminal 2 — tạo server\nnc -l 9000\n\n# Terminal 3 — connect để xem handshake\nnc 127.0.0.1 9000\n# tcpdump hiển thị: SYN → SYN-ACK → ACK"
    },
    {
      "step": 3,
      "what": "Thử UDP — không có handshake",
      "why": "Thấy rõ sự khác biệt: UDP gửi thẳng không cần server sẵn sàng. Nếu server chưa lắng nghe, gói vẫn gửi đi — UDP không báo lỗi. Đây là lý do cần timeout ở tầng app khi dùng UDP.",
      "whyBreaks": "Gửi UDP khi không có server listen → không báo lỗi ở phía gửi (khác TCP refused ngay). Kernel đích gửi ICMP Port Unreachable — nhưng nếu firewall block ICMP thì sender không biết gì. Debug UDP failure khó hơn TCP vì thiếu connection state.",
      "observeWith": "sudo tcpdump -i lo -n 'port 9001' -v  # Xem UDP datagram không có handshake flags\nss -ulnp  # Kiểm tra UDP socket đang listen",
      "code": "# Terminal 1 — UDP server\nnc -u -l 9000\n\n# Terminal 2 — UDP client (không handshake)\nnc -u 127.0.0.1 9000\n# Gõ text → hiện ở Terminal 1 ngay, không cần bắt tay trước\n\n# So sánh: gửi UDP khi không có server\nnc -u 127.0.0.1 9001  # port chưa mở\necho 'hello' | nc -u 127.0.0.1 9001  # gửi không báo lỗi",
      "failModes": [
        {
          "symptom": "UDP client gửi data nhưng server không nhận — không có báo lỗi nào ở client",
          "evidence": "sudo tcpdump -i lo -n 'port 9001' thấy UDP packet đi ra nhưng không có packet về. Server side không in gì. Không có error message ở client — đây là behavior by design của UDP best-effort"
        },
        {
          "symptom": "UDP gửi không lỗi nhưng server log thiếu message",
          "evidence": "Đếm số message gửi vs số nhận: client gửi 1000 gói, server log chỉ thấy 950 — 50 gói bị drop silently (packet loss 5%). Phát hiện bằng application-level sequence counter, UDP không tự báo"
        }
      ],
      "fixSteps": [
        {
          "step": "Dùng tcpdump để xác nhận UDP packet có thực sự được gửi đi không",
          "command": "sudo tcpdump -i lo -n 'udp port 9001' -c 5"
        },
        {
          "step": "Nếu cần delivery guarantee với UDP, implement sequence number ở tầng app",
          "command": "# Không có lệnh OS — đây là logic phải implement trong application code"
        }
      ]
    },
    {
      "step": 4,
      "what": "So sánh TCP vs UDP với Wireshark / tcpdump",
      "why": "Wireshark hiển thị đúng số RTT: TCP thấy 3 packet đầu là handshake trước khi data. UDP thấy data ngay packet đầu tiên. Đây là bằng chứng trực tiếp về trade-off latency.",
      "whyBreaks": "Nếu chỉ capture một bên mà không thấy ACK → network asymmetric (gói một chiều bị block). Common khi debug cloud VM: inbound OK nhưng outbound bị chặn bởi security group → SYN đi nhưng không có SYN-ACK về.",
      "observeWith": "sudo tcpdump -i lo -n 'port 9000 or port 9001'  # So sánh cùng lúc\n# TCP: thấy [S] [S.] [.] trước data | UDP: thấy data packet đầu tiên ngay",
      "code": "# Capture cả TCP và UDP cùng lúc\nsudo tcpdump -i lo -n 'port 9000 or port 9001'\n\n# Mở 2 cặp server/client (TCP port 9000, UDP port 9001)\n# TCP: nc -l 9000  /  nc 127.0.0.1 9000\n# UDP: nc -u -l 9001  /  nc -u 127.0.0.1 9001\n\n# Quan sát: TCP bắt đầu bằng 3 dòng SYN/SYN-ACK/ACK\n# UDP bắt đầu thẳng bằng data packet"
    },
    {
      "step": 5,
      "what": "Kiểm tra port đang listen — phân biệt TCP/UDP",
      "why": "ss/netstat phân biệt tcp vs udp trong output. Khi debug 'connection refused', bước đầu tiên là kiểm tra process nào đang listen port nào, bằng giao thức nào.",
      "whyBreaks": "Service chạy trên UDP nhưng client connect TCP → refused ngay. Xảy ra khi cấu hình sai: DNS server (UDP 53) bị test bằng nc (TCP mặc định) → refused nhưng DNS vẫn hoạt động. Kiểm tra đúng protocol trước khi kết luận service down.",
      "observeWith": "ss -tlunp  # t=TCP, u=UDP, l=listening, n=numeric, p=process\n# Output phân biệt rõ 'tcp' vs 'udp' ở cột đầu",
      "code": "# Xem tất cả port đang listen (cả TCP lẫn UDP)\nss -tlunp\n\n# Xem riêng TCP\nss -tlnp | grep LISTEN\n\n# Xem riêng UDP\nss -ulnp\n\n# Xem process nào bind port cụ thể\nsudo ss -tlnp | grep ':80'"
    },
    {
      "step": 6,
      "what": "DNS query qua UDP — thấy tại sao không cần TCP",
      "why": "DNS là ví dụ kinh điển nhất cho UDP: query và response fit vào 1 packet &lt;512 byte. Dùng dig với +tcp để so sánh latency — TCP thêm handshake overhead rõ ràng.",
      "whyBreaks": "Firewall block UDP 53 outbound → mọi DNS query timeout → toàn bộ service phụ thuộc domain resolution đều fail. Dấu hiệu: ping IP OK nhưng ping hostname timeout. Verify: dig @8.8.8.8 google.com nếu không trả lời → firewall block UDP 53.",
      "observeWith": "sudo tcpdump -i any -n 'port 53'  # Capture DNS: xem UDP vs TCP handshake\ndig google.com  # Default UDP\ndig +tcp google.com  # Force TCP — đếm số packet thêm",
      "code": "# DNS query mặc định dùng UDP\ndig google.com\n\n# Force DNS qua TCP để so sánh\ndig +tcp google.com\n\n# Capture DNS query (UDP port 53)\nsudo tcpdump -i any -n 'port 53' &\ndig google.com\nsudo pkill tcpdump\n# Thấy: 1 query packet + 1 response packet (UDP, không có handshake)"
    },
    {
      "step": 7,
      "what": "TCP FIN handshake — đóng kết nối đúng cách",
      "why": "TCP không chỉ bắt tay khi mở mà còn khi đóng: FIN → FIN-ACK → ACK. Hiểu TIME_WAIT giúp debug 'Address already in use' khi restart server — kernel chờ hết TIME_WAIT (60s).",
      "whyBreaks": "Restart service ngay sau khi dừng → 'Address already in use' vì port vẫn ở TIME_WAIT. Fix: SO_REUSEADDR (hầu hết production server đã set). Nếu thấy quá nhiều TIME_WAIT → có thể connection không được reuse (thiếu keepalive/connection pool).",
      "observeWith": "ss -tn state time-wait  # Xem connection đang ở TIME_WAIT\nwatch -n1 'ss -tn | grep TIME-WAIT | wc -l'  # Đếm real-time khi open/close connection",
      "code": "# Xem TCP states khi kết nối đóng\nss -tn\n\n# Xem TIME_WAIT (xuất hiện ngay sau khi đóng kết nối)\nss -tn | grep TIME-WAIT\n\n# Fix 'Address already in use' khi dev: SO_REUSEADDR\n# (nginx, node.js đều set flag này mặc định)",
      "failModes": [
        {
          "symptom": "Server không nhận được connection mới dù đang chạy — client báo 'cannot assign requested address'",
          "evidence": "ss -tn | grep TIME-WAIT | wc -l trả về hàng chục nghìn (>28000 trên default ephemeral range 32768-60999). Client kernel không tìm được port ephemeral trống để mở connection mới"
        },
        {
          "symptom": "Restart nginx/node ngay sau khi stop → 'bind: Address already in use'",
          "evidence": "ss -tn | grep ':80.*TIME-WAIT' hoặc ss -tlnp | grep ':80' không thấy LISTEN nhưng port vẫn bị chiếm. Kernel giữ socket ở TIME_WAIT ~60s (2×MSL, RFC 793)"
        }
      ],
      "fixSteps": [
        {
          "step": "Kiểm tra số lượng TIME_WAIT hiện tại",
          "command": "ss -tn state time-wait | wc -l"
        },
        {
          "step": "Xem range ephemeral port của kernel",
          "command": "cat /proc/sys/net/ipv4/ip_local_port_range"
        },
        {
          "step": "Tăng ephemeral port range để có nhiều port hơn (tạm thời, cần tune keepalive/pool là giải pháp thực sự)",
          "command": "sudo sysctl -w net.ipv4.ip_local_port_range='1024 65535'"
        },
        {
          "step": "Bật tcp_tw_reuse để tái dùng TIME_WAIT socket cho outbound connection (an toàn khi enable timestamps)",
          "command": "sudo sysctl -w net.ipv4.tcp_tw_reuse=1"
        }
      ],
      "automateScript": {
        "lang": "bash",
        "code": "#!/bin/bash\n# watch-tcp-states.sh — Monitor TCP state counts theo thời gian thực\n# Dùng khi debug TIME_WAIT exhaustion hoặc theo dõi connection leak\nINTERVAL=${1:-2}\necho \"Monitoring TCP states every ${INTERVAL}s (Ctrl+C để dừng)\"\necho \"---\"\nwhile true; do\n  echo \"$(date '+%H:%M:%S')  $(ss -tn | awk 'NR>1{print $1}' | sort | uniq -c | sort -rn | tr '\\n' '  ')\"\n  sleep \"$INTERVAL\"\ndone",
        "note": "Chạy trên production server khi nghi ngờ TIME_WAIT exhaustion hoặc connection pool leak. Output: timestamp + count từng TCP state (ESTAB, TIME-WAIT, CLOSE-WAIT...). Interval mặc định 2s, truyền tham số để thay đổi: ./watch-tcp-states.sh 5"
      }
    }
  ],
  "quiz": [
    {
      "q": "Tại sao DNS dùng UDP thay vì TCP?",
      "options": [
        "UDP bảo mật hơn TCP",
        "DNS query nhỏ, cần nhanh — tránh overhead 3-way handshake",
        "TCP không hỗ trợ port 53",
        "UDP đảm bảo delivery tốt hơn TCP"
      ],
      "correct": 1,
      "whyCorrect": "DNS query thường &lt;512 byte và cần trả lời trong vài ms. Nếu dùng TCP phải tốn 3 packet handshake trước mỗi query — gần gấp đôi latency. Với hàng tỷ query/giây, tiết kiệm handshake = tiết kiệm khổng lồ.",
      "whyOthersWrong": {
        "0": "UDP không bảo mật hơn TCP. Nếu cần bảo mật DNS thì dùng DNS-over-TLS (DoT) hoặc DNS-over-HTTPS (DoH), đều chạy trên TCP/HTTPS.",
        "2": "TCP hoàn toàn hỗ trợ port 53. DNS over TCP (dùng cho zone transfer và response &gt;512 byte) vẫn dùng port 53.",
        "3": "Ngược lại — UDP không đảm bảo delivery. TCP mới đảm bảo. UDP được chọn vì tốc độ, không phải reliability."
      }
    },
    {
      "q": "3-way handshake của TCP diễn ra theo thứ tự nào?",
      "options": [
        "SYN-ACK → SYN → ACK",
        "ACK → SYN → SYN-ACK",
        "SYN → SYN-ACK → ACK",
        "SYN → ACK → DATA"
      ],
      "correct": 2,
      "whyCorrect": "Client gửi SYN (xin kết nối). Server phản hồi SYN-ACK (đồng ý + xin ngược lại). Client ACK (xác nhận). Thứ tự này đảm bảo cả 2 hướng đều hoạt động trước khi data đi.",
      "whyOthersWrong": {
        "0": "SYN-ACK không thể là bước đầu vì server không biết ai cần kết nối cho đến khi nhận SYN.",
        "1": "ACK đầu tiên không có ý nghĩa — ACK là xác nhận, nhưng chưa có gì để xác nhận.",
        "3": "Sau SYN và ACK vẫn thiếu SYN-ACK từ server — kết nối chưa được server đồng ý."
      }
    },
    {
      "q": "Lỗi 'Connection refused' xuất hiện khi curl một server. Nguyên nhân khả năng nhất là gì?",
      "options": [
        "Firewall chặn packet",
        "DNS không resolve được hostname",
        "Không có process nào đang listen trên port đó",
        "Cáp mạng bị đứt"
      ],
      "correct": 2,
      "whyCorrect": "'Connection refused' = TCP SYN tới được máy đích nhưng kernel gửi RST vì không có process listen port đó. Nghĩa là máy sống, IP route OK, nhưng service chưa chạy (hoặc chạy sai port).",
      "whyOthersWrong": {
        "0": "Firewall DROP packet thì ra 'connection timeout' (SYN bị nuốt), không phải 'refused'. Nếu firewall REJECT thì ra ICMP unreachable, không phải TCP RST.",
        "1": "DNS fail thì curl báo 'Could not resolve host', không phải 'Connection refused'. DNS xảy ra trước khi TCP connect.",
        "3": "Cáp đứt → link down → không route được → timeout hoặc 'no route to host'. Packet không tới đích."
      }
    },
    {
      "q": "HTTP/3 dùng UDP thay vì TCP — tại sao không dùng TCP như HTTP/1 và HTTP/2?",
      "options": [
        "UDP nhanh hơn và HTTP/3 không cần reliability",
        "TCP có Head-of-Line blocking — mất 1 packet chặn toàn bộ connection",
        "UDP được IANA khuyến nghị cho HTTPS",
        "TCP không hỗ trợ port 443"
      ],
      "correct": 1,
      "whyCorrect": "HTTP/2 multiplex nhiều stream trên 1 TCP connection. Khi mất 1 TCP packet, toàn bộ connection phải chờ retransmit — cả những stream khác không liên quan cũng bị block (Head-of-Line blocking). QUIC trên UDP tự xử lý từng stream độc lập.",
      "whyOthersWrong": {
        "0": "HTTP/3 vẫn cần reliability — QUIC tự implement reliability ở tầng app, không bỏ reliability. Chỉ là không dùng TCP để làm điều đó.",
        "2": "IANA không khuyến nghị UDP cho HTTPS. Quyết định này của Google (QUIC) và sau đó IETF chuẩn hóa thành HTTP/3.",
        "3": "TCP hoàn toàn hỗ trợ port 443. HTTP/1.1 và HTTP/2 vẫn dùng TCP:443 tới ngày nay."
      }
    },
    {
      "q": "Well-known ports (0–1023) cần quyền root để bind — tại sao?",
      "options": [
        "Để tăng hiệu suất network",
        "Bảo vệ khỏi user thường giả mạo service hệ thống (SSH, HTTP)",
        "Vì số port nhỏ cần bộ nhớ kernel riêng",
        "IANA quy định chỉ kernel được dùng"
      ],
      "correct": 1,
      "whyCorrect": "Nếu bất kỳ user nào bind được :22, họ có thể tạo SSH server giả mạo — lấy credential. Chỉ root process mới tin tưởng được chạy SSH thật. Đó là lý do nginx production chạy với root rồi drop privilege sau khi bind :80/:443.",
      "whyOthersWrong": {
        "0": "Port number không ảnh hưởng đến hiệu suất network. Packet routing không quan tâm port nhỏ hay lớn.",
        "2": "Kernel không dùng bộ nhớ riêng cho port nhỏ. Port chỉ là số 16-bit trong header.",
        "3": "IANA gán tên service cho port nhưng không kiểm soát OS policy. Quyết định cần root là của OS kernel (Linux, BSD, Windows)."
      }
    },
    {
      "q": "Debug một game multiplayer bị lag cao. Developer cho biết 'server dùng TCP'. Vấn đề có thể là gì?",
      "options": [
        "TCP không hỗ trợ nhiều kết nối đồng thời",
        "TCP retransmit khi mất gói — đây làm tăng latency không kiểm soát được trong game",
        "Game không thể dùng TCP, chỉ có UDP",
        "TCP header quá lớn gây tắc nghẽn"
      ],
      "correct": 1,
      "whyCorrect": "Trong game, mỗi frame position cũ đều vô giá trị khi frame mới tới. TCP retransmit gói cũ làm delay mọi gói mới sau đó (Head-of-Line blocking). Game nên dùng UDP và tự handle mất gói — bỏ qua frame cũ, chỉ quan tâm frame mới nhất.",
      "whyOthersWrong": {
        "0": "TCP hỗ trợ hàng nghìn kết nối đồng thời. Multiplayer server dùng TCP vẫn hoạt động được về số lượng connection.",
        "2": "Game có thể dùng TCP — nhiều game mobile thực tế dùng TCP cho casual gaming. Vấn đề là latency, không phải tính tương thích.",
        "3": "TCP header 20-60 byte không đủ lớn để gây tắc nghẽn. Latency chủ yếu từ retransmit logic, không phải header size."
      }
    },
    {
      "q": "Điều gì xảy ra khi gửi UDP packet đến một port không có process listen?",
      "options": [
        "Gói bị drop silently, không có phản hồi gì",
        "Kết nối timeout sau 30 giây",
        "ICMP Port Unreachable được gửi về",
        "OS tự redirect sang port khác"
      ],
      "correct": 2,
      "whyCorrect": "Khi UDP packet đến port không listen, kernel gửi ICMP Type 3 Code 3 (Port Unreachable) về cho sender. Đây là lý do 'nc -u 127.0.0.1 [closed-port]' thường nhận ICMP error ngay — khác với TCP RST.",
      "whyOthersWrong": {
        "0": "Không phải luôn silent — kernel gửi ICMP Port Unreachable về. Tuy nhiên firewall có thể block ICMP, làm bên gửi không nhận được phản hồi.",
        "1": "UDP không có timeout built-in. Timeout 30s là behavior của application, không phải kernel/protocol.",
        "3": "OS không redirect port — đó là chức năng của application proxy hoặc NAT rule."
      }
    },
    {
      "q": "Sequence number trong TCP dùng để làm gì?",
      "options": [
        "Định danh connection (thay IP)",
        "Đảm bảo thứ tự và phát hiện mất gói để retransmit",
        "Mã hóa dữ liệu",
        "Đếm số byte đã gửi để tính bandwidth"
      ],
      "correct": 1,
      "whyCorrect": "Sequence number đánh số từng byte. Receiver biết gói nào đến thiếu (ACK gói cuối nhận được liên tiếp). Khi mạng reorder packet, receiver dùng seq number để sắp xếp lại đúng thứ tự. Đây là cơ chế cốt lõi làm TCP reliable.",
      "whyOthersWrong": {
        "0": "Connection được định danh bằng 4-tuple: src IP, src port, dst IP, dst port. Sequence number không dùng cho mục đích này.",
        "2": "Sequence number không mã hóa gì. Encryption ở TLS (L5/L6), không liên quan TCP header.",
        "3": "Sequence number là byte offset, không phải counter đo bandwidth. Throughput được tính từ ACK timing, không từ seq number trực tiếp."
      }
    }
  ],
  "flashcards": [
    {
      "front": "TCP là gì và khi nào dùng?",
      "back": "Transmission Control Protocol — kết nối có xác nhận, đảm bảo thứ tự và delivery. Dùng cho web (HTTP/S), SSH, database, email — bất cứ khi nào mất 1 byte là hỏng.",
      "why": "Không biết khi nào dùng TCP thì thiết kế service sẽ sai từ đầu — như dùng UDP cho database query."
    },
    {
      "front": "UDP là gì và khi nào dùng?",
      "back": "User Datagram Protocol — gửi không xác nhận, không đảm bảo thứ tự. Dùng cho DNS, VoIP, video streaming, game online — khi latency quan trọng hơn mất vài byte.",
      "why": "Dùng sai UDP (cho web) làm trang web hiển thị sai/thiếu. Dùng sai TCP (cho game) làm lag do retransmit."
    },
    {
      "front": "3-way handshake TCP gồm những gì?",
      "back": "1. Client → Server: SYN (seq=X)\n2. Server → Client: SYN-ACK (seq=Y, ack=X+1)\n3. Client → Server: ACK (ack=Y+1)\nSau đó data bắt đầu đi.",
      "why": "3 bước này đảm bảo cả 2 hướng client→server và server→client đều thông trước khi gửi data thật. Nếu chỉ 1 bước (SYN+DATA) thì server có thể nhận data mà client không biết server có nhận không."
    },
    {
      "front": "Connection refused vs Connection timeout khác nhau thế nào?",
      "back": "Refused: SYN tới đích, kernel trả TCP RST — máy sống nhưng không có process listen port đó.\nTimeout: SYN không bao giờ nhận ACK — firewall drop, máy tắt, hoặc route sai.",
      "why": "Phân biệt được 2 lỗi này giúp debug đúng hướng: refused → kiểm tra service có chạy không; timeout → kiểm tra firewall/network/IP."
    },
    {
      "front": "Well-known ports là gì? Tại sao cần root?",
      "back": "Port 0–1023, được IANA gán cho service nổi tiếng (22=SSH, 53=DNS, 80=HTTP, 443=HTTPS). Cần root để bind vì bảo vệ khỏi user thường giả mạo service hệ thống.",
      "why": "Nếu không cần root, bất kỳ user nào cũng tạo SSH server giả trên :22 để lấy password — đây là lý do restriction tồn tại."
    },
    {
      "front": "Tại sao HTTP/3 dùng UDP?",
      "back": "HTTP/2 trên TCP bị Head-of-Line blocking: mất 1 TCP packet → block toàn bộ connection dù có nhiều stream. QUIC (HTTP/3) trên UDP tự xử lý từng stream độc lập — mất 1 stream không ảnh hưởng stream khác.",
      "why": "Hiểu điều này giải thích tại sao HTTP/3 nhanh hơn HTTP/2 trong môi trường mạng kém (mobile, Wi-Fi yếu) — môi trường hay mất gói."
    },
    {
      "front": "Sequence number trong TCP làm gì?",
      "back": "Đánh số từng byte data. Receiver ACK số byte cuối nhận liên tiếp. Sender retransmit nếu không nhận ACK. Dùng để reorder khi packet đến không đúng thứ tự.",
      "why": "Đây là cơ chế cốt lõi giúp TCP reliable — không có seq number thì không biết gói nào mất, không reorder được."
    },
    {
      "front": "TIME_WAIT state trong TCP là gì?",
      "back": "Sau khi đóng kết nối, socket ở TIME_WAIT trong ~60s. Kernel chờ để đảm bảo không có packet cũ lạc đường nào đến sau.",
      "why": "Hiểu TIME_WAIT giúp debug 'Address already in use' khi restart server — dùng SO_REUSEADDR để bypass. Không hiểu sẽ mất thời gian chờ không cần thiết."
    },
    {
      "front": "TCP window size là gì?",
      "back": "Số byte sender có thể gửi trước khi cần ACK. Window size lớn = throughput cao. Receiver quảng bá window size để kiểm soát flow (flow control).",
      "why": "Bandwidth cao nhưng latency cao (satellite) → TCP slow vì window size giới hạn throughput. Đây là lý do cần TCP tuning (tcp_rmem/tcp_wmem) cho long-fat networks."
    },
    {
      "front": "UDP checksum bảo vệ gì?",
      "back": "8-byte UDP header gồm src port, dst port, length, checksum. Checksum phát hiện corruption trong transit — nhưng không retransmit. App tự quyết định bỏ qua hay xử lý.",
      "why": "UDP không hoàn toàn vô trách nhiệm — checksum vẫn có. Điểm khác biệt: corrupt packet bị drop không retransmit, app phải tự retry nếu cần."
    },
    {
      "front": "nc -l 9000 vs nc -u -l 9000 khác nhau thế nào?",
      "back": "nc -l 9000: TCP server, client phải handshake trước khi gửi.\nnc -u -l 9000: UDP server, nhận datagram thẳng không handshake.",
      "why": "Phân biệt flag -u quan trọng khi test service. Dùng nc để debug nhanh mà không cần viết code — là skill tối thiểu của sysadmin/DevOps."
    },
    {
      "front": "Port range: well-known, registered, ephemeral?",
      "back": "0–1023: well-known (IANA, cần root)\n1024–49151: registered (ứng dụng thường, không cần root)\n49152–65535: ephemeral (OS tự gán cho client connections)",
      "why": "Khi debug netstat/ss, thấy port client >49152 là bình thường — đó là ephemeral port OS tự assign. Không cần lo lắng về port số lớn phía client."
    }
  ],
  "try_at_home": [
    {
      "cmd": "# Terminal 1: start TCP server\nnc -l 9000\n\n# Terminal 2: capture\nsudo tcpdump -i lo -n 'port 9000' -v\n\n# Terminal 3: connect\nnc 127.0.0.1 9000",
      "why": "Thấy tận mắt 3-way handshake — SYN/SYN-ACK/ACK — trước khi data đi",
      "observeWith": "# Trong output tcpdump nhìn flags:\n# [S] = SYN (client xin kết nối)\n# [S.] = SYN-ACK (server đồng ý)\n# [.] = ACK (client xác nhận)\n# Đếm 3 dòng này = 3-way handshake hoàn tất trước data đầu tiên"
    },
    {
      "cmd": "# Terminal 1: UDP server\nnc -u -l 9001\n\n# Terminal 2: capture\nsudo tcpdump -i lo -n 'port 9001' -v\n\n# Terminal 3: UDP client\nnc -u 127.0.0.1 9001",
      "why": "Thấy UDP không có handshake — data đi thẳng không cần bắt tay",
      "observeWith": "# Trong tcpdump: packet đầu tiên là DATA ngay\n# Không có [S] [S.] [.] nào — đây là bằng chứng UDP fire-and-forget\nss -ulnp | grep 9001  # Verify UDP server đang listen"
    },
    {
      "cmd": "sudo tcpdump -i any -n 'port 53' &\ndig google.com\nsudo pkill tcpdump\n# So sánh: dig +tcp google.com (force TCP, thấy SYN trước)",
      "why": "Thấy DNS dùng UDP (port 53) — query + response chỉ 2 packet, không có handshake",
      "observeWith": "# UDP DNS: chỉ 2 dòng trong tcpdump (query + response)\n# TCP DNS: thêm 3 dòng handshake trước 2 dòng data\ndig +stats google.com  # Xem 'SERVER:' và 'Query time:' để so sánh latency"
    },
    {
      "cmd": "# Xem tất cả TCP port đang LISTEN\nss -tlnp\n\n# Xem tất cả UDP socket\nss -ulnp\n\n# Xem process bind port cụ thể\nsudo ss -tlnp | grep ':80'",
      "why": "Kiểm tra port đang listen để phân biệt TCP vs UDP — kỹ năng debug cơ bản",
      "observeWith": "# Cột đầu tiên: 'tcp' hoặc 'udp' — đây là cách phân biệt\n# State 'LISTEN' chỉ có với TCP; UDP không có LISTEN state\n# Cột 'Local Address:Port' cho biết IP và port đang bind"
    },
    {
      "cmd": "# Connection refused: port không có process listen\nnc -vz 127.0.0.1 65533\n\n# Connection timeout: IP không tồn tại hoặc firewall drop\nnc -vz -w 3 203.0.113.254 80\n\n# Quan sát thời gian phản hồi: refused ngay lập tức, timeout sau 3s",
      "why": "Tái hiện 'connection refused' vs 'connection timeout' — 2 lỗi hay gặp nhất",
      "observeWith": "# Refused: trả lời ngay trong <10ms — kernel gửi RST\n# Timeout: chờ đủ -w giây — SYN bị drop/firewall\ntime nc -vz 127.0.0.1 65533  # Đo thời gian refused\ntime nc -vz -w 2 203.0.113.254 80  # Đo thời gian timeout"
    },
    {
      "cmd": "# Xem tất cả TCP connections với state\nss -tn\n\n# Lọc theo state\nss -tn state established\nss -tn state time-wait\n\n# Watch real-time khi mở/đóng connection\nwatch -n1 'ss -tn | head -20'",
      "why": "Xem TCP states trong hệ thống — hiểu ESTABLISHED, TIME_WAIT, LISTEN",
      "observeWith": "# Sau khi đóng nc connection: xem TIME-WAIT xuất hiện\n# ss -tn | grep TIME-WAIT — tồn tại ~60s trước khi biến mất\n# Đây chính là nguyên nhân 'Address already in use' khi restart nhanh"
    }
  ],
  "diagram": {
    "type": "custom",
    "component": "TcpUdpPlayground"
  }
};

export default lab;
