import type { LabContent } from '../../app/src/lib/schema-lab';

// Auto-generated by scripts/fixtures-to-ts.mjs — DO NOT EDIT MANUALLY
// Source: fixtures/labs/tcp-ip-packet-journey.json

const lab: LabContent = {
  "id": 1,
  "slug": "tcp-ip-packet-journey",
  "module": "01-networking",
  "title": "Lý thuyết OSI TCP/IP",
  "file_path": "labs/01-networking/01-tcp-ip-packet-journey.html",
  "estimated_minutes": 40,
  "content_hash": "3ca1b104e8ed29008894dfab27522a58e7263a09",
  "updated_at": 1776596703,
  "tldr": [
    {
      "why": "Nơi application 'nói chuyện' — HTTP request, gửi email, query DNS. Lỗi 400/500/502 không phải lỗi mạng — là app hoặc server có vấn đề.",
      "whyBreaks": "Nhầm lỗi Application thành lỗi mạng → debug sai hướng hàng giờ. Lỗi 502 Bad Gateway là Application layer fail, không phải cáp mạng vấn đề. Nếu thiếu hiểu biết tầng này, sẽ restart server vô ích thay vì check log nginx/app.",
      "deploymentUse": "Khi VPS deploy xong, check log application trước: journalctl -u nginx, docker logs <container>. Lỗi 502/503 luôn là Application hoặc Transport, không phải Link/Internet.",
      "layer": "L4",
      "name": "Application",
      "pdu": "Message",
      "device": "Process (nginx, curl, ping...)",
      "protocol": "HTTP, DNS, SSH, TLS, FTP"
    },
    {
      "why": "Như số phòng trong tòa nhà — PORT giúp 1 máy chạy nhiều service (web :80, SSH :22). TCP đảm bảo dữ liệu đến đủ và đúng thứ tự. UDP nhanh hơn nhưng không đảm bảo.",
      "whyBreaks": "Nếu không hiểu tầng Transport, khi port bị chặn sẽ không biết tại sao curl fail dù ping OK. Cài nginx nhưng quên mở port 80/443 trong firewall = Transport bị chặn = toàn bộ HTTP traffic chết.",
      "deploymentUse": "Sau khi start nginx trên VPS, luôn kiểm tra: ss -tlnp | grep 80 (service đang listen?) và nc -vz <ip> 80 từ máy client (port mở từ ngoài?). Hai bước này xác nhận Transport layer OK.",
      "layer": "L3",
      "name": "Transport",
      "pdu": "Segment / Datagram",
      "device": "Kernel OS",
      "protocol": "TCP, UDP"
    },
    {
      "why": "Địa chỉ IP giúp packet 'tìm đường' xuyên qua nhiều mạng — từ máy local đến server ở nước ngoài. Router dựa vào IP để biết chuyển packet đi đâu tiếp.",
      "whyBreaks": "Sai routing table hoặc sai default gateway → packet không ra được internet dù WiFi 'connected'. Nhiều lần 'mạng không vào được' thực ra là default gateway chết hoặc routing table sai — không phải cáp mạng.",
      "deploymentUse": "Khi VPS không ra được internet: ip route (có default route chưa?), ping 8.8.8.8 (Internet layer OK?), ping 8.8.4.4 (không phụ thuộc DNS). Nếu ping IP được nhưng domain không được = DNS fail, không phải Internet layer.",
      "layer": "L2",
      "name": "Internet",
      "pdu": "Packet",
      "device": "Router",
      "protocol": "IP, ICMP"
    },
    {
      "why": "Tầng 'vật lý' — cáp mạng, WiFi, card mạng. Dùng địa chỉ MAC để gửi dữ liệu giữa 2 máy cùng mạng LAN. Cáp đứt hoặc WiFi mất sóng thì 3 tầng trên đều vô dụng.",
      "whyBreaks": "Link fail = mọi thứ trên vô nghĩa. Trên VPS cloud, Link thường do provider quản lý nhưng vẫn có thể fail do NIC driver, MTU mismatch, hoặc cloud security group block ở L2.",
      "deploymentUse": "ip link show — xem interface có UP không. Nếu state DOWN thì Link chết. Trên AWS/GCP, security group rule chặn ở đây — nhưng error giống như Network Unreachable, không phải Connection Refused.",
      "layer": "L1",
      "name": "Link",
      "pdu": "Frame / Bits",
      "device": "NIC, switch, cáp, WiFi",
      "protocol": "Ethernet, WiFi 802.11"
    }
  ],
  "walkthrough": [
    {
      "step": 0,
      "what": "Bước 0: DNS — đổi tên miền thành địa chỉ IP",
      "why": "Máy tính KHÔNG hiểu <code>example.com</code>. Mọi kết nối đều cần IP (ví dụ <code>93.184.216.34</code>). Trước khi ping được, OS phải hỏi DNS server: 'example.com là IP gì?'. Khi internet chập chờn, lỗi <strong>'could not resolve host'</strong> thường xuất hiện — đó là DNS chết, chưa đến lượt ping chạy.",
      "whyBreaks": "Bỏ qua DNS lookup khi debug → không phát hiện DNS fail, cứ nghĩ là lỗi mạng. 'Could not resolve host' LUÔN là DNS vấn đề, không phải cáp đứt. Nếu ping IP trực tiếp được nhưng ping domain fail = DNS chết.",
      "observeWith": "dig example.com +short — xem IP trả về và thời gian query. Nếu chỉ thấy SERVFAIL hoặc không trả về IP thì DNS resolver đang có vấn đề. Thử dig example.com @8.8.8.8 để bypass resolver của ISP.",
      "code": "# Hỏi DNS thủ công\ndig example.com +short\n\n# Hoặc cách cũ hơn\nnslookup example.com",
      "failModes": [
        {
          "symptom": "curl/ping báo 'could not resolve host example.com'",
          "evidence": "dig example.com trả về: ;; connection timed out; no servers could be reached  hoặc status: SERVFAIL"
        },
        {
          "symptom": "DNS query trả về IP sai (poisoned/cache stale)",
          "evidence": "dig example.com +short trả về IP không khớp với dig example.com @8.8.8.8 +short"
        }
      ],
      "fixSteps": [
        {
          "step": "Kiểm tra DNS resolver đang dùng",
          "command": "cat /etc/resolv.conf"
        },
        {
          "step": "Bypass resolver ISP, query thẳng 8.8.8.8",
          "command": "dig example.com @8.8.8.8 +short"
        },
        {
          "step": "Nếu resolver là systemd-resolved, kiểm tra trạng thái",
          "command": "systemd-resolve --status | grep 'DNS Servers'"
        }
      ]
    },
    {
      "step": 1,
      "what": "Tầng 4 Application: lệnh ping tạo ICMP echo request",
      "why": "Lệnh <code>ping</code> là 1 chương trình ở tầng Application. Nó không tự gửi được gì — nó gọi kernel: 'gửi ICMP echo tới IP X'. ICMP là protocol đặc biệt: nằm trong tầng Internet chứ không phải Transport (nên ping không có 'port').",
      "whyBreaks": "Nghĩ ping test được toàn bộ stack → bỏ qua việc test TCP port sau khi deploy. Ping ICMP và TCP 80/443 là 2 việc khác nhau. Firewall hay chặn ICMP cho phép TCP hoặc ngược lại.",
      "observeWith": "ping -c 4 example.com — nhìn time= (RTT) và packet loss %. Nếu 0% loss và time <100ms thì Internet layer hoàn toàn ổn. Nếu time >500ms thì có vấn đề về routing hoặc server bị quá tải.",
      "code": "# Ping 4 gói rồi dừng (Linux/Mac)\nping -c 4 example.com\n\n# Windows\nping -n 4 example.com"
    },
    {
      "step": 2,
      "what": "Tầng 2 Internet: OS đóng gói IP header",
      "why": "Kernel gắn IP header với: <code>Source IP</code> = địa chỉ của máy (ví dụ 192.168.1.10), <code>Destination IP</code> = 93.184.216.34, <code>TTL = 64</code>. TTL giảm 1 mỗi router — cơ chế chống loop vô tận, và cũng là thứ <code>traceroute</code> lợi dụng để nhìn thấy từng router trên đường đi.",
      "whyBreaks": "Không biết IP của máy = không biết Source IP trong packet = không debug được 'tại sao server từ chối kết nối'. NAT sẽ đổi Source IP → server thấy IP khác với IP client. Nhầm IP private và public dẫn đến cấu hình firewall sai.",
      "observeWith": "ip route get 8.8.8.8 — xem Linux chọn interface và gateway nào để gửi packet tới 8.8.8.8. Output 'via X.X.X.X dev ethY src Z.Z.Z.Z' cho biết gateway, NIC card, và source IP cho kết nối này.",
      "code": "# Xem IP của máy\nip addr show   # Linux\nifconfig       # Mac\nipconfig       # Windows\n\n# Xem bảng routing — máy sẽ gửi gói đi đâu?\nip route       # Linux\nnetstat -rn    # Mac\nroute print    # Windows"
    },
    {
      "step": 3,
      "what": "Tầng 1 Link: đóng thành Ethernet frame + hỏi MAC qua ARP",
      "why": "IP là địa chỉ logic. Để gửi bit trên cáp/WiFi phải có địa chỉ <strong>vật lý</strong> (MAC). Host dùng giao thức <code>ARP</code> broadcast hỏi 'Ai có IP 192.168.1.1 (gateway)?' — gateway trả lời kèm MAC. Lưu ý: MAC đích là MAC của <strong>gateway</strong> (vì server ở xa), không phải MAC của server. Đây là chỗ dev hay nhầm.",
      "whyBreaks": "ARP poisoning là attack phổ biến trong LAN: kẻ tấn công gửi ARP reply giả → host gửi traffic tới MAC của attacker thay vì gateway → MITM. Trong môi trường cloud, ARP giữa VM thường bị cloud platform quản lý — cần biết điều này khi debug.",
      "observeWith": "ip neigh show — xem ARP table. Nếu thấy gateway IP với trạng thái REACHABLE thì Link layer tới gateway OK. FAILED hoặc INCOMPLETE = ARP không resolve được = Link layer có vấn đề.",
      "code": "# Xem ARP cache (IP ↔ MAC đã biết trong LAN)\nip neigh show     # Linux\narp -a            # Mac/Windows\n\n# Xem MAC của máy\nip link show\nifconfig | grep ether"
    },
    {
      "step": 4,
      "what": "Đi qua Internet: router chuyển tiếp theo IP",
      "why": "Router nhận frame → bóc lấy IP packet → đọc Destination IP → tra bảng routing → đóng frame mới với MAC của hop tiếp theo → gửi đi. TTL giảm 1. Lặp lại qua N router tới khi gói tới mạng của server. Đây là bản chất của 'Internet' = liên mạng.",
      "whyBreaks": "Không biết traceroute → khi debug 'tại sao latency cao' hoặc 'packet drop ở đâu' chỉ biết nhìn chứ không tìm được bottleneck. Traceroute tiết lộ đúng router nào đang slow hoặc drop packet.",
      "observeWith": "traceroute -n example.com (-n không resolve hostname, nhanh hơn) — xem từng hop latency. Nếu 1 hop đột ngột tăng từ 10ms lên 200ms = bottleneck tại đó. * * * = router block ICMP, không có nghĩa là down.",
      "code": "# Xem đường đi thật, từng hop\ntraceroute example.com     # Linux/Mac\ntracert example.com        # Windows\n\n# Nếu traceroute dừng nửa chừng = router trên đường block ICMP/UDP\nsudo traceroute -T -p 443 example.com"
    },
    {
      "step": 5,
      "what": "Server bóc ngược: Link → Internet → nhận ICMP → reply",
      "why": "Server example.com nhận frame → check MAC (đúng của server) → bóc IP header → check Dest IP (đúng của server) → thấy protocol là ICMP → kernel tự trả lời bằng ICMP echo <em>reply</em> (không cần app nào tham gia). Đây là lý do ping hoạt động ngay cả khi server không chạy web/ssh — chỉ cần kernel sống.",
      "whyBreaks": "Không dùng tcpdump → không biết packet có tới server không → debug blind. Khi 'curl không được', tcpdump trên server cho biết ngay: packet có tới không? Tới mà không reply = process chết. Không tới = firewall chặn trước server.",
      "observeWith": "sudo tcpdump -i any -n 'tcp port 80' — chạy khi client curl http://server. Nếu thấy SYN tới nhưng không có SYN-ACK thì không có process listen. Nếu không thấy SYN nào = packet chưa tới, chặn ở đâu đó trước.",
      "code": "# Trên server, xem packet đến bằng tcpdump\nsudo tcpdump -i any -n 'icmp'\n# Output 2 dòng mỗi lần ping:\n# IP <client> > <server>: ICMP echo request\n# IP <server> > <client>: ICMP echo reply",
      "failModes": [
        {
          "symptom": "tcpdump chạy nhưng không hiển thị packet nào dù biết traffic đang chạy",
          "evidence": "tcpdump -i eth0 không capture, nhưng tcpdump -i any có — do sai interface. Kiểm tra: ip link show để xem tên interface đúng"
        },
        {
          "symptom": "sudo tcpdump báo 'eth0: No such device'",
          "evidence": "ip link show không liệt kê interface tên eth0 — NIC có thể tên ens3, enp0s3, hoặc tên predictable khác theo udev"
        }
      ],
      "fixSteps": [
        {
          "step": "Liệt kê interface thực tế trên máy",
          "command": "ip link show"
        },
        {
          "step": "Dùng -i any để capture trên mọi interface",
          "command": "sudo tcpdump -i any -n 'icmp' -c 10"
        }
      ],
      "automateScript": {
        "lang": "bash",
        "code": "#!/bin/bash\n# Rotate tcpdump capture theo size — tránh đầy disk\n# Dùng khi cần capture dài hạn (debug production)\n# Mỗi file tối đa 100MB, giữ 5 file gần nhất\nINTERFACE=${1:-any}\nOUTDIR=${2:-/tmp/tcpdump-captures}\nmkdir -p \"$OUTDIR\"\nsudo tcpdump -i \"$INTERFACE\" -n \\\n  -C 100 \\\n  -W 5 \\\n  -w \"$OUTDIR/capture.pcap\" \\\n  &\necho \"tcpdump PID=$! | captures in $OUTDIR | max 5x100MB\"",
        "note": "Chạy thủ công khi debug production traffic. -C 100 = rotate mỗi 100MB, -W 5 = giữ 5 file. Dừng bằng kill $PID. Phân tích sau với: tcpdump -r /tmp/tcpdump-captures/capture.pcap0"
      }
    },
    {
      "step": 6,
      "what": "Reply về: ping in ra '64 bytes from ... time=12.3 ms'",
      "why": "Số <code>time=</code> là round-trip time (RTT) — tổng thời gian đi + về. <code>ttl=</code> là TTL còn lại khi tới máy nhận → đoán được số hop (ví dụ ttl=54 và server dùng TTL mặc định 64 → đã qua 10 router). Đây là cách đo <strong>độ trễ vật lý</strong> của internet.",
      "whyBreaks": "Không biết đọc ping output → bỏ qua packet loss và jitter quan trọng. Packet loss 1-2% trên TCP làm tốc độ giảm rất nhiều (TCP retransmit). Jitter cao = không ổn định, ảnh hưởng video call/realtime app.",
      "observeWith": "ping -c 100 example.com — ping 100 gói để thấy thống kê chính xác. Cuối output có min/avg/max/mdev. mdev lớn = jitter cao = mạng không ổn định. Packet loss > 0% = có vấn đề nghiêm trọng.",
      "code": "# Ping dài hạn để thấy jitter / packet loss\nping example.com\n\n# Ping với size lớn để test MTU\nping -s 1472 example.com"
    },
    {
      "step": 7,
      "what": "🆚 Tại sao curl có thể fail dù ping thành công?",
      "why": "<strong>Đây là insight chính.</strong> Ping chỉ test tầng Internet. Curl/browser cần <em>thêm</em>:<br>• <strong>Transport (TCP)</strong>: bắt tay 3 bước tới port 80/443. Firewall chặn port → <code>connection timeout</code>. Máy sống nhưng không có nginx → <code>connection refused</code>.<br>• <strong>Application (HTTP)</strong>: server phải trả HTTP hợp lệ. Nginx trả 500 → ping OK, curl báo 500.<br>Khi deploy VPS mà 'ping được, curl không được', biết ngay vấn đề ở <strong>Transport hoặc Application</strong>, không phải mạng.",
      "whyBreaks": "Không biết test từng tầng riêng biệt → khi debug chỉ biết 'không vào được' mà không biết vấn đề ở tầng nào. Tệ hơn, có thể restart toàn bộ hệ thống vô ích trong khi chỉ cần mở port firewall.",
      "observeWith": "nc -vz <ip_vps> 80 — nếu 'succeeded' = Transport OK, nginx đang listen. Nếu 'refused' = nginx chưa start hoặc sai port. Nếu timeout sau 5-10s = firewall đang chặn port 80.",
      "code": "# Test Transport layer riêng (không cần HTTP)\nnc -vz example.com 443    # Linux/Mac\nTest-NetConnection example.com -Port 443   # Windows PowerShell\n\n# Test cả Application\ncurl -v https://example.com"
    }
  ],
  "quiz": [
    {
      "q": "Khi gõ <code>ping example.com</code>, tầng nào trong TCP/IP 4 KHÔNG được sử dụng?",
      "options": [
        "Link",
        "Internet",
        "Transport",
        "Application"
      ],
      "correct": 2,
      "whyCorrect": "ICMP (protocol của ping) nằm ngay ở tầng Internet, không qua Transport (TCP/UDP). Đó là lý do ping không có khái niệm 'port'.",
      "whyOthersWrong": {
        "0": "Link luôn được dùng — không có nó bit không lên được cáp/WiFi.",
        "1": "Internet là tầng chính của ping — IP header và ICMP đều ở đây.",
        "3": "Lệnh ping chính là process ở tầng Application gọi xuống kernel."
      }
    },
    {
      "q": "Deploy app lên VPS. Từ máy client: ping &lt;ip_vps&gt; OK, nhưng <code>curl http://&lt;ip_vps&gt;</code> báo 'connection refused'. Vấn đề ở tầng nào?",
      "options": [
        "Link — cáp mạng VPS lỏng",
        "Internet — routing sai",
        "Transport — không có process listen port 80",
        "Application — trả về 500"
      ],
      "correct": 2,
      "whyCorrect": "Ping OK = Link + Internet OK, VPS sống. 'Connection refused' = TCP SYN tới nơi nhưng kernel VPS trả RST vì không có process listen port 80. Có thể nginx chưa chạy / chạy nhầm port.",
      "whyOthersWrong": {
        "0": "Link hỏng thì ping cũng fail.",
        "1": "Routing sai thì ping cũng fail.",
        "3": "Muốn nhận 500 phải kết nối TCP thành công trước → không ra 'refused'."
      }
    },
    {
      "q": "TCP/IP 4 layer vs OSI 7 layer khác nhau ở đâu?",
      "options": [
        "TCP/IP là lý thuyết, OSI được triển khai thực tế",
        "TCP/IP gộp L5/L6/L7 của OSI thành Application, và L1+L2 thành Link",
        "Chúng hoàn toàn giống nhau, chỉ khác tên",
        "Cả hai đều có 4 tầng"
      ],
      "correct": 1,
      "whyCorrect": "TCP/IP 4 tầng = Application (gộp L5+L6+L7 OSI) + Transport (L4) + Internet (L3) + Link (L1+L2). Đây là mô hình thực tế đang chạy. OSI là mô hình tham chiếu lý thuyết.",
      "whyOthersWrong": {
        "0": "Ngược lại — TCP/IP thực tế, OSI lý thuyết.",
        "2": "Số tầng khác nhau.",
        "3": "OSI có 7 tầng."
      }
    },
    {
      "q": "Host gửi frame ra internet. MAC địa chỉ đích trong Ethernet frame là gì?",
      "options": [
        "MAC của server đích",
        "MAC của gateway (router mạng LAN)",
        "Broadcast FF:FF:FF:FF:FF:FF",
        "MAC của host gửi"
      ],
      "correct": 1,
      "whyCorrect": "Frame chỉ đi trong 1 mạng LAN. Ra ngoài phải nhờ gateway. ARP chỉ hỏi được MAC trong LAN, nên frame đầu tiên có MAC đích = MAC gateway. Gateway bóc frame, đóng frame mới với MAC hop tiếp theo.",
      "whyOthersWrong": {
        "0": "Host không biết MAC server ở mạng khác — ARP không chạy xuyên router.",
        "2": "Broadcast chỉ dùng cho ARP/DHCP discovery.",
        "3": "Đó là MAC source, không phải destination."
      }
    },
    {
      "q": "<code>curl example.com</code> báo 'could not resolve host'. Vấn đề ở tầng nào?",
      "options": [
        "Link — cáp lỏng",
        "Internet — IP routing hỏng",
        "Application — DNS không trả về IP",
        "Transport — TCP bắt tay fail"
      ],
      "correct": 2,
      "whyCorrect": "DNS là protocol ở tầng Application. 'Could not resolve host' = curl không lấy được IP → chưa tới Internet/Transport. Thường do DNS server không phản hồi hoặc /etc/resolv.conf sai.",
      "whyOthersWrong": {
        "0": "Link hỏng thì error khác, thường 'network unreachable'.",
        "1": "Chưa tới Internet — chưa có IP để route.",
        "3": "Chưa đến TCP — chưa có IP đích để bắt tay."
      }
    },
    {
      "q": "Vì sao TCP/IP tách Transport (port) ra khỏi Internet (IP)?",
      "options": [
        "Để bảo mật hơn",
        "Vì 1 máy có 1 IP nhưng chạy nhiều service — port phân biệt nginx:80, ssh:22, mysql:3306",
        "Vì router cần cả IP và port để routing",
        "Vì IPv4 không đủ port"
      ],
      "correct": 1,
      "whyCorrect": "Lý do tồn tại của Transport chính là đa service trên 1 host. IP đưa gói tới đúng máy, port đưa gói tới đúng process.",
      "whyOthersWrong": {
        "0": "Port không làm tăng bảo mật — kẻ xấu quét port rất dễ.",
        "2": "Router thường chỉ đọc IP (trừ NAT nâng cao).",
        "3": "IP và port là 2 khái niệm khác nhau."
      }
    },
    {
      "q": "Ping 1 IP, thấy reply có <code>ttl=54</code>. Điều này nói lên gì?",
      "options": [
        "Packet còn sống 54 giây nữa",
        "Packet đã đi qua khoảng 10 router (nếu OS đích đặt TTL mặc định 64)",
        "Kết nối còn giữ được 54 lần nữa",
        "Không có ý nghĩa gì"
      ],
      "correct": 1,
      "whyCorrect": "TTL giảm 1 mỗi router. Nhiều OS đặt TTL ban đầu = 64 (Linux/Mac) hoặc 128 (Windows). ttl=54 ở client, đoán server dùng 64 → đã qua 10 hop. Cách đoán kiểu OS + độ xa mà không cần traceroute.",
      "whyOthersWrong": {
        "0": "TTL đơn vị là 'số hop', không phải giây (dù tên là Time To Live).",
        "2": "TTL tính trên từng gói, không phải cả 'kết nối'.",
        "3": "Có ý nghĩa — chính là số hop đã đi."
      }
    },
    {
      "q": "Rút cáp mạng / tắt WiFi. Error nào xuất hiện SỚM NHẤT khi gõ curl?",
      "options": [
        "Connection timeout",
        "Could not resolve host (DNS fail)",
        "TLS handshake failed",
        "Network is unreachable — báo ngay lập tức"
      ],
      "correct": 3,
      "whyCorrect": "Link layer fail là kernel nhận ra ngay (interface state down). Curl hỏi kernel 'gửi đi' và kernel trả 'không có đường đi' — không phải chờ gì. Các lỗi kia đều cần timeout hoặc phản hồi từ bên ngoài.",
      "whyOthersWrong": {
        "0": "Timeout cần chờ vài giây tới vài chục giây.",
        "1": "DNS fail cũng cần chờ timeout.",
        "2": "TLS ở tầng Application, xa lắm mới tới."
      }
    }
  ],
  "flashcards": [
    {
      "front": "TCP/IP có mấy tầng? Kể tên từ thấp lên cao.",
      "back": "4 tầng: Link → Internet → Transport → Application.",
      "why": "Đây là mô hình THỰC TẾ của internet. Nhớ 4 tầng này là đủ làm việc; OSI 7 chỉ để tham chiếu lý thuyết."
    },
    {
      "front": "Tầng Link làm gì?",
      "back": "Đẩy bit/frame giữa 2 thiết bị CÙNG LAN. Dùng MAC address. Tương ứng OSI L1 + L2.",
      "why": "Link fail = mọi thứ trên vô nghĩa. Luôn debug Link trước (đèn NIC, ip link, WiFi)."
    },
    {
      "front": "Tầng Internet làm gì?",
      "back": "Định tuyến packet XUYÊN nhiều mạng bằng IP address. Protocol: IP, ICMP (ping). Tương ứng OSI L3.",
      "why": "Tầng tạo ra 'Inter-net' (liên mạng). Không có nó mỗi LAN là 1 ốc đảo."
    },
    {
      "front": "Tầng Transport làm gì?",
      "back": "Chia data thành segment (TCP) / datagram (UDP), gắn PORT để phân biệt service. Tương ứng OSI L4.",
      "why": "1 máy nhiều service → port là cách duy nhất phân biệt nginx:80 vs ssh:22 vs mysql:3306."
    },
    {
      "front": "Tầng Application gồm những gì?",
      "back": "HTTP, DNS, SSH, TLS, FTP, SMTP... Tất cả protocol dev code hằng ngày. Tương ứng OSI L5+L6+L7.",
      "why": "Dev làm việc 90% ở tầng này. Lỗi 400/500 là Application, KHÔNG phải lỗi mạng."
    },
    {
      "front": "Ping dùng protocol gì? Ở tầng nào?",
      "back": "ICMP (Internet Control Message Protocol) — ở tầng INTERNET, không qua Transport.",
      "why": "Vì thế ping không có port. Firewall có thể cho ping qua nhưng chặn TCP — dẫn tới 'ping được, curl không được'."
    },
    {
      "front": "Ping được + curl báo 'connection refused' = ?",
      "back": "Link + Internet OK. Vấn đề ở Transport: máy đích sống nhưng không có process listen port đó.",
      "why": "Hay gặp khi deploy VPS: quên start nginx, hoặc nginx nghe port khác. Không phải lỗi mạng."
    },
    {
      "front": "Ping được + curl báo 'connection timeout' = ?",
      "back": "Link + Internet OK, nhưng TCP SYN không tới được process. Thường do firewall chặn port.",
      "why": "Phân biệt refused vs timeout là kỹ năng debug cốt lõi: refused = máy sống, timeout = firewall hoặc mạng chặn."
    },
    {
      "front": "DNS nằm ở tầng nào?",
      "back": "Application. DNS là protocol ở tầng Application, chạy trên UDP port 53.",
      "why": "Lỗi 'could not resolve host' = DNS fail = chưa tới lượt Internet/Transport. Debug bằng dig/nslookup."
    },
    {
      "front": "Khi frame ra khỏi LAN, MAC đích là gì?",
      "back": "MAC của GATEWAY, KHÔNG phải MAC của server đích.",
      "why": "ARP chỉ hỏi được trong LAN. Ra ngoài, gateway bóc frame rồi đóng lại với MAC mới cho hop tiếp theo."
    },
    {
      "front": "TTL trong IP header để làm gì?",
      "back": "Giới hạn số hop packet đi qua. Mỗi router giảm 1, tới 0 thì drop → tránh loop vô tận.",
      "why": "Traceroute khai thác TTL: gửi TTL=1,2,3... để 'dụ' từng router báo lỗi Time Exceeded → biết đường đi."
    },
    {
      "front": "Encapsulation là gì?",
      "back": "Mỗi tầng bọc header riêng của nó vào gói tin của tầng trên. Xuống = thêm header. Lên = bóc header.",
      "why": "Tách tầng để đổi 1 tầng không ảnh hưởng tầng khác. Đổi WiFi → cáp không cần sửa HTTP."
    },
    {
      "front": "Vì sao TCP/IP 'thắng' OSI trong thực tế?",
      "back": "TCP/IP có implementation chạy thật (ARPANET → Internet). OSI ra sau, quá chi tiết, chưa kịp phổ biến.",
      "why": "Hôm nay: code và tool đều chạy trên TCP/IP. OSI còn dùng làm 'ngôn ngữ chung' khi nói 'lỗi ở layer mấy'."
    },
    {
      "front": "Gateway / default route là gì?",
      "back": "Router mặc định nhận mọi packet có IP đích NGOÀI LAN. Xem bằng <code>ip route</code>.",
      "why": "Gateway chết = mất hết internet dù WiFi vẫn 'connected'. Thủ phạm số 1 khi host không ra được internet."
    }
  ],
  "try_at_home": [
    {
      "cmd": "ping -c 4 example.com",
      "why": "Lệnh cơ bản nhất — xem máy đích có sống + đo độ trễ",
      "observeWith": "Nhìn time= (RTT) và packet loss. RTT <50ms = gần, >200ms = xa hoặc chậm. Packet loss > 0% là dấu hiệu đáng lo. Ctrl+C để dừng, ping sẽ in thống kê min/avg/max."
    },
    {
      "cmd": "dig example.com +short\n# hoặc\nnslookup example.com",
      "why": "Đổi tên miền thành IP — cơ sở cho mọi kết nối",
      "observeWith": "dig example.com +short chỉ in IP, không thêm. Thử dig example.com (không +short) để xem TTL và server đang dùng. Nếu không có output = DNS fail hoàn toàn."
    },
    {
      "cmd": "ip addr show       # Linux\nifconfig           # Mac\nipconfig /all      # Windows",
      "why": "Xem IP + MAC của máy — biết host là ai trong mạng",
      "observeWith": "Tìm interface có state UP và có inet (IPv4). Lưu ý phân biệt IP private (192.168.x.x, 10.x.x.x, 172.16-31.x.x) và public. MAC address hiển thị sau 'ether' (Linux) hoặc 'Physical Address' (Windows)."
    },
    {
      "cmd": "ip route           # Linux\nnetstat -rn        # Mac\nroute print        # Windows",
      "why": "Xem gateway mặc định — 'cửa ra' internet của host",
      "observeWith": "Tìm dòng 'default via X.X.X.X' (Linux) hoặc '0.0.0.0' destination (Windows). IP sau 'via' là gateway. Ping gateway đó: nếu không ping được = Link/Internet tới gateway chết = không ra được internet."
    },
    {
      "cmd": "traceroute example.com     # Linux/Mac\ntracert example.com        # Windows",
      "why": "Xem đường đi thật của packet qua từng router",
      "observeWith": "Mỗi dòng là 1 router hop với latency. Tìm điểm latency tăng đột ngột — đó là bottleneck. '* * *' không có nghĩa là down, chỉ là router không reply ICMP. Hop cuối = server đích hoặc gần đó."
    },
    {
      "cmd": "# Refused: máy sống, port không ai nghe\nnc -vz 127.0.0.1 65000\n\n# Timeout: IP không tồn tại\nnc -vz -w 3 203.0.113.254 80",
      "why": "Phân biệt 'connection refused' vs 'timeout' bằng thực nghiệm — debug cốt lõi",
      "observeWith": "nc -vz 127.0.0.1 65000 sẽ báo 'refused' ngay lập tức (<1s). nc -vz -w 3 <ip-ko-tồn-tại> 80 sẽ chờ 3 giây rồi timeout. Tốc độ phản hồi là dấu hiệu quan trọng để phân biệt."
    },
    {
      "cmd": "sudo tcpdump -i any -n 'icmp' -c 10",
      "why": "Xem packet đến/đi bằng tcpdump — công cụ debug mạng level devops",
      "observeWith": "Khi tcpdump đang chạy, mở terminal khác ping example.com. Output sẽ hiển thị 2 dòng mỗi ping: 'echo request' (đi) và 'echo reply' (về). Chỉ thấy request mà không có reply = firewall chặn return traffic."
    }
  ],
  "diagram": {
    "type": "custom",
    "component": "TcpIpJourneyPlayground"
  }
};

export default lab;
