/**
 * fixtures-to-ts.mjs
 *
 * Reads fixtures/labs/*.json, validates via Zod (lab-schema.js),
 * and writes content/labs/{slug}.ts type-safe TypeScript files.
 *
 * Usage:
 *   node scripts/fixtures-to-ts.mjs
 *   node scripts/fixtures-to-ts.mjs --dry-run
 *   node scripts/fixtures-to-ts.mjs --slug=dns
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { resolve, join, dirname } from 'path';
import { fileURLToPath } from 'url';

// ── Resolve paths ─────────────────────────────────────────────────────────────

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const FIXTURES_DIR = join(ROOT, 'fixtures', 'labs');
const OUTPUT_DIR = join(ROOT, 'content', 'labs');

// ── Parse CLI flags ───────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const isDryRun = args.includes('--dry-run');
const slugArg = args.find((a) => a.startsWith('--slug='))?.split('=')[1] ?? null;

// ── Load Zod schema (CJS-compatible via dynamic import) ───────────────────────

const { LabFixtureSchema } = await import('./lab-schema.js');

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Generate a TypeScript file content for a single lab fixture.
 * Uses JSON.stringify to safely escape all string content
 * (handles backticks, ${}, quotes, control chars).
 *
 * JSON is a valid subset of TS object literals when fed to tsc,
 * since JSON.stringify never emits trailing commas or undefined values.
 */
function generateTsContent(fixture) {
  const jsonBody = JSON.stringify(fixture, null, 2);
  return [
    `import type { LabContent } from '../../app/src/lib/schema-lab';`,
    ``,
    `// Auto-generated by scripts/fixtures-to-ts.mjs — DO NOT EDIT MANUALLY`,
    `// Source: fixtures/labs/${fixture.slug}.json`,
    ``,
    `const lab: LabContent = ${jsonBody};`,
    ``,
    `export default lab;`,
    ``,
  ].join('\n');
}

// ── Main ──────────────────────────────────────────────────────────────────────

let files = readdirSync(FIXTURES_DIR).filter((f) => f.endsWith('.json'));

// Filter by --slug flag
if (slugArg) {
  files = files.filter((f) => f === `${slugArg}.json`);
  if (files.length === 0) {
    console.error(`[fixtures-to-ts] No fixture found for slug: ${slugArg}`);
    process.exit(1);
  }
}

if (!isDryRun) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

let successCount = 0;
let errorCount = 0;

for (const file of files) {
  const filePath = join(FIXTURES_DIR, file);
  const slug = file.replace('.json', '');

  let raw;
  try {
    raw = JSON.parse(readFileSync(filePath, 'utf-8'));
  } catch (err) {
    console.error(`[fixtures-to-ts] Failed to read/parse ${file}: ${err.message}`);
    errorCount++;
    continue;
  }

  const result = LabFixtureSchema.safeParse(raw);
  if (!result.success) {
    console.error(`[fixtures-to-ts] Validation failed for ${file}:`);
    for (const issue of result.error.issues) {
      console.error(`  - ${issue.path.join('.')} : ${issue.message}`);
    }
    errorCount++;
    continue;
  }

  const tsContent = generateTsContent(result.data);
  const outPath = join(OUTPUT_DIR, `${slug}.ts`);

  if (isDryRun) {
    console.log(`[dry-run] Would write: ${outPath}`);
    console.log(`--- preview (first 6 lines) ---`);
    console.log(tsContent.split('\n').slice(0, 6).join('\n'));
    console.log('---');
  } else {
    try {
      writeFileSync(outPath, tsContent, 'utf-8');
      console.log(`[fixtures-to-ts] Written: content/labs/${slug}.ts`);
      successCount++;
    } catch (err) {
      console.error(`[fixtures-to-ts] Failed to write ${outPath}: ${err.message}`);
      errorCount++;
    }
  }
}

if (!isDryRun) {
  console.log(`\n[fixtures-to-ts] Done — ${successCount} written, ${errorCount} errors.`);
}

if (errorCount > 0) {
  process.exit(1);
}
